In [41]:
#Import pandas & datetime packages
import pandas as pd
import datetime as dt

#Display all values
pd.set_option('display.max_rows',None)

In [42]:
hospital_stays=pd.read_csv('/Users/aaronless/Desktop/Data Analysis Porfolio Projects/Other/Hospital Stays/Original CSVs/hospital_stays.csv')
hospital_stays.head(50)

,stay_id,patient_id,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis_code,diagnosis_description,attending_physician,room_type,discharge_status,total_charge_usd,readmission_within_30_days
0,S007869,PT-01674,2025-09-26,2025-09-29,3.0,Emergency,Behavioral Health,F19.20,Substance use / overdose,NaN,ICU,Discharged - Home,4169.1,N
1,S000352,PT02670,01/11/2025,16-Jan-2025,5.0,Urgent,PULMONOLOGY,J44.1,COPD exacerbation,Dr. Voss,Semi-Private,Discharged - Home,"$13,031.58",N
2,S007291,PT-03216,09/04/2025,2025-09-06,2.0,Elective,Cardiology,R07.9,"Chest pain, observation",Dr. Novak,Semi-Private,Discharged - Home,"$3,988.81",N
3,S002933,pt-02352,03-23-2025,03-26-2025,NaN,Urgent,UROLOGY,N20.0,Kidney stones,Dr. Kim,Ward,Discharged - Home,"$5,865.28",N
4,S007038,PT-02472,08-26-2025,08/31/2025,5.0,Emergency,Endocrinology,E11.9,Diabetes with complications,Dr. Patel,Semi-Private,Discharged - SNF,14533.41,N
5,S009678,PT-02493,2025-11-28,30-Nov-2025,NaN,Urgent,Oncology,Z51.11,Chemotherapy admission,Dr. Fitzgerald,Private,Discharged - SNF,10536.61,N
6,S004525,PT-01595,"May 19, 2025",05-24-2025,5.0,Elective,General Surgery,K81.0,Acute cholecystitis,Dr. Delgado,Private,Home Health Care,17936.7,N
7,S006779,PT-01010,15-Aug-2025,17-Aug-2025,2.0,Emergency,Cardiology,R07.9,"CHEST PAIN, OBSERVATION",Dr. Bianchi,Semi-Private,Discharged - Home,"$4,035.01",N
8,S002679,PT-03836,03/16/2025,03/18/2025,2.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Osborne,Private,Discharged - Home,"$4,890.55",N
9,S006853,PT-00288,08-19-2025,08-22-2025,3.0,Urgent,Urology,N20.0,Kidney stones,Dr. Kim,Ward,Home Health Care,"$5,951.77",N
10,S009139,PT-02969,11-11-2025,15-Nov-2025,4.0,Urgent,Pulmonology,J11.1,INFLUENZA WITH COMPLICATIONS,Dr. Voss,Semi-Private,Discharged - Home,8199.89,N
11,S007256,PT-03421,"September 02, 2025",07-Sep-2025,5.0,Elective,Orthopedics,Z96.641,Elective total hip replacement,Dr. Petrov,Semi-Private,Discharged - Home,19900.49,N
12,S006664,PT-02586,2025-08-11,16-Aug-2025,5.0,Urgent,PULMONOLOGY,J11.1,Influenza with complications,Dr. Osborne,Private,NaN,11663.16,N
13,S006852,PT-03608,08-19-2025,"August 21, 2025",2.0,Emergency,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Private,Discharged - Home,"$5,476.93",N
14,S003609,PT-01784,14-Apr-2025,16-Apr-2025,2.0,Emergency,Behavioral Health,F19.20,Substance use / overdose,Dr. Chen,ICU,Discharged - Home,"$3,642.94",N
15,S002496,PT-01623,10-Mar-2025,03/16/2025,6.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Bianchi,Private,Discharged - Rehab,28656.88,Yes
16,S002391,PT-00111,03/07/2025,13-Mar-2025,6.0,Emergency,pulmonology,J18.9,Pneumonia,Dr. Castillo,Private,Discharged - Home,11475.38,N
17,S005754,PT-03306,07-06-2025,07-07-2025,1.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Semi-Private,Discharged - Home,"$1,584.61",N
18,S002341,pt-03871,2025-03-05,"March 08, 2025",3.0,Emergency,Internal Medicine,L03.90,Cellulitis,Dr. Sorensen,Semi-Private,Discharged - Home,"$5,980.90",Y
19,S006012,PT-04013,16-Jul-2025,2025-07-20,4.0,Urgent,Endocrinology,E11.9,Diabetes with complications,Dr. Mendez,Private,Discharged - Home,6800.4,y
20,S000685,PT-03851,2025-01-20,01/23/2025,3.0,Urgent,Pulmonology,J18.9,Pneumonia,Dr. Ibrahim,Semi-Private,Discharged - SNF,8463.89,N
21,S006762,PT-00619,"August 15, 2025",20-Aug-2025,5.0,Urgent,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Private,Home Health Care,"$12,702.60",N
22,S006422,PT-01525,2025-08-01,"August 05, 2025",4.0,Urgent,Cardiology,I48.91,Atrial fibrillation,Dr. Reyes,Semi-Private,NaN,"$12,816.24",N
23,S002406,PT-02935,03-08-2025,2025-03-10,2.0,Emergency,Obstetrics,O14.90,Preeclampsia,Dr. Larsen,ICU,Discharged - Home,"$6,792.49",N
24,S005239,PT-00666,06-16-2025,2025-06-19,3.0,Emergency,Cardiology,I48.91,Atrial fibrillation,Dr. Novak,Semi-Private,Home Health Care,9175.59,N
25,S008001,PT-02610,"October 02, 2025",10/04/2025,2.0,Elective,Oncology,Z51.11,Chemotherapy admission,Dr. Voss,Private,Discharged - Home,"$10,598.38",N
26,S007186,PT-03773,08/31/2025,2025-09-01,1.0,Elective,INTERNAL MEDICINE,N39.0,urinary tract infection,Dr. Mendez,Semi-Private,Discharged - Home,2051.34,N
27,S005854,PT-02713,07/10/2025,2025-07-16,6.0,Emergency,TRAUMA,V89.2XXA,Motor vehicle accident trauma,Dr. Mendez,ICU,Discharged - Home,23874.13,N
28,S007469,pt-01170,11-Sep-2025,14-Sep-2025,3.0,Emergency,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Semi-Private,Discharged - Home,9629.17,Yes
29,S007009,PT-02034,25-Aug-2025,2025-09-02,8.0,Emergency,Neurology,I63.9,Ischemic stroke,Dr. Silva,ICU,Discharged - Home,"$52,622.33",N
30,S001686,pt-01922,16-Feb-2025,2025-02-18,2.0,Elective,Pulmonology,J45.901,asthma exacerbation,Dr. Kowalski,Ward,Home Health Care,4497.05,N
31,S002884,PT-00915,22-Mar-2025,03-25-2025,3.0,Urgent,Pulmonology,U07.1,COVID-19,Dr. Voss,Semi-Private,NaN,"$9,690.55",N
32,S008144,PT03502,07-Oct-2025,10/12/2025,5.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Okafor,Private,Transferred,"$34,487.89",N
33,S008285,PT-04155,2025-10-13,24-Oct-2025,11.0,Urgent,Cardiology,I50.9,Congestive heart failure,Dr. Okafor,ICU,Discharged - Rehab,"$44,121.88",N
34,S003447,PT-01317,04/09/2025,04-13-2025,NaN,Urgent,Internal Medicine,L03.90,Cellulitis,Dr. Mendez,Ward,Discharged - Home,"$7,846.32",N
35,S006696,PT02521,12-Aug-2025,"August 13, 2025",1.0,Elective,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Semi-Private,Discharged - Home,"$2,298.57",N
36,S003309,pt-01199,04-04-2025,04/09/2025,5.0,Elective,Internal Medicine,N39.0,Urinary tract infection,Dr. Mendez,Semi-Private,Discharged - Home,10730.36,N
37,S002306,PT-03661,2025-03-05,"March 07, 2025",2.0,Urgent,Pulmonology,J18.9,Pneumonia,Dr. Kowalski,Private,Discharged - Home,3758.73,N
38,S003117,PT-03354,03/29/2025,02-Apr-2025,4.0,Urgent,Pulmonology,J44.1,COPD exacerbation,Dr. Ibrahim,Private,Left AMA,8690.29,N
39,S003992,pt-03514,04-27-2025,"May 01, 2025",4.0,Elective,Pulmonology,U07.1,COVID-19,Dr. Castillo,Private,Discharged - Home,11126.04,N
40,S006701,PT-03976,08/12/2025,2025-08-21,9.0,Emergency,endocrinology,E11.9,Diabetes with complications,Dr. Haddad,Semi-Private,Discharged - Home,16501.25,N
41,S005755,PT-00776,07/06/2025,"July 09, 2025",3.0,Elective,Orthopedics,Z96.651,Elective total knee replacement,Dr. Whitfield,Private,Discharged - Home,"$13,098.57",Y
42,S009331,PT-03775,11-17-2025,"November 20, 2025",NaN,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Ward,Discharged - Home,6923.17,N
43,S009744,PT-00868,11-30-2025,12/02/2025,2.0,Urgent,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Ward,Discharged - Home,4829.67,N
44,S005915,PT-02591,"July 13, 2025",07/18/2025,NaN,Emergency,Nephrology,N18.9,chronic kidney disease exacerbation,Dr. Sorensen,Private,Discharged - Home,19210.72,N
45,S006573,PT-02076,"August 06, 2025",08/07/2025,1.0,Emergency,Urology,N20.0,Kidney stones,Dr. Voss,Ward,Home Health Care,"$2,313.78",N
46,S005419,PT-04086,06/22/2025,06-24-2025,2.0,Elective,Orthopedics,Z96.651,elective total knee replacement,Dr. Whitfield,Private,Discharged - Home,"$7,289.17",N
47,S000651,PT-02371,2025-01-19,24-Jan-2025,5.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Kowalski,Private,NaN,"$8,442.58",N
48,S008392,PT-01350,"October 17, 2025","October 21, 2025",4.0,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Semi-Private,Discharged - Home,5067.42,N
49,S009451,PT00091,11/20/2025,11/25/2025,5.0,Emergency,Cardiology,I48.91,Atrial fibrillation,Dr. Okafor,Private,Discharged - Home,17223.3,N

In [43]:
#Identify any duplicate entries within the data
stay_duplicates=hospital_stays.duplicated()
hospital_stays[stay_duplicates].sort_values(by='stay_id')

,stay_id,patient_id,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis_code,diagnosis_description,attending_physician,room_type,discharge_status,total_charge_usd,readmission_within_30_days
4676,S000044,PT-03961,02-Jan-2025,01/05/2025,3.0,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Novak,Semi-Private,Discharged - Home,3955.88,N
2997,S000122,pt-01640,01-04-2025,NaN,3.0,Urgent,General Surgery,K35.80,Appendicitis,NaN,Semi-Private,Home Health Care,"$7,836.58",N
10547,S000182,PT-02778,"January 06, 2025","January 12, 2025",6.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Bianchi,ICU,NaN,"$52,632.73",N
6634,S000213,PT-02857,2025-01-07,11-Jan-2025,4.0,Emergency,Behavioral Health,F32.2,Major depressive episode,Dr. Bianchi,Semi-Private,Discharged - Home,"$6,107.13",N
8716,S000409,PT-03186,"January 13, 2025",15-Jan-2025,2.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Ward,Discharged - Home,"$4,887.98",N
3426,S000431,PT-03310,01/13/2025,2025-01-18,5.0,Emergency,Pulmonology,J18.9,Pneumonia,Dr. Voss,Private,Discharged - Home,"$15,230.72",N
5502,S000478,PT-02371,2025-01-14,01/16/2025,2.0,Emergency,CARDIOLOGY,I21.9,Acute myocardial infarction,Dr. Okafor,ICU,Discharged - SNF,"$17,018.24",N
1813,S000486,PT-01134,01/15/2025,"January 22, 2025",7.0,Emergency,Neurology,I63.9,Ischemic stroke,NaN,Private,Discharged - Home,"$27,524.41",N
3137,S000626,pt-02386,01-19-2025,2025-01-24,5.0,Emergency,Pulmonology,J44.1,COPD exacerbation,Dr. Kowalski,Private,Left AMA,13780.5,N
6718,S000690,PT-04062,01-20-2025,01-21-2025,1.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Novak,Ward,Discharged - Home,1713.18,N
10143,S000716,PT-00771,01/21/2025,01-26-2025,5.0,Emergency,Cardiology,I50.9,Congestive heart failure,Dr. Reyes,ICU,Discharged - SNF,16929.45,N
9440,S000980,PT-00776,2025-01-28,"February 01, 2025",4.0,Elective,Internal Medicine,L03.90,cellulitis,Dr. Mendez,Semi-Private,Discharged - Home,"$6,493.58",Y
10582,S001123,PT-02938,02-01-2025,"February 07, 2025",6.0,Emergency,Neurology,I63.9,Ischemic stroke,Dr. Osei,ICU,Discharged - Home,33688.01,N
7346,S001125,PT-00841,02-01-2025,02-Feb-2025,1.0,Emergency,Urology,N20.0,Kidney stones,Dr. Abbas,Semi-Private,NaN,2166.01,N
8501,S001213,PT-03175,02/03/2025,02-08-2025,5.0,Elective,Pulmonology,J11.1,Influenza with complications,Dr. Kowalski,Semi-Private,Discharged - Home,"$8,741.28",N
9033,S001573,PT-01193,"February 13, 2025","February 15, 2025",2.0,Emergency,Internal Medicine,L03.90,Cellulitis,Dr. Mendez,Ward,NaN,"$3,502.54",N
3658,S001627,PT-01066,02/14/2025,02-19-2025,5.0,Emergency,Gastroenterology,K92.2,GI bleed,Dr. Silva,ICU,Discharged - Home,"$16,460.23",No
2138,S001709,PT00118,"February 17, 2025","February 20, 2025",3.0,Urgent,PULMONOLOGY,J45.901,Asthma exacerbation,Dr. Castillo,Semi-Private,Discharged - Home,"$6,060.13",N
10051,S001730,PT-02193,2025-02-17,2025-02-19,2.0,Emergency,Pediatrics,J21.9,Bronchiolitis (pediatric),Dr. Larsen,Semi-Private,Discharged - Home,"$2,993.08",N
5006,S001791,PT-00414,"February 18, 2025",23-Feb-2025,5.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Ibrahim,Semi-Private,Discharged - Home,12428.5,N
9838,S002050,PT-03326,02/25/2025,03/02/2025,5.0,Emergency,Internal Medicine,A41.9,Sepsis,Dr. Sorensen,Private,Transferred,"$37,934.01",No
6570,S002188,PT-01371,2025-03-01,2025-03-06,5.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Bianchi,ICU,Discharged - Home,"$27,945.64",y
6111,S002239,PT03712,03-03-2025,03-07-2025,4.0,Elective,Cardiology,I48.91,Atrial fibrillation,Dr. Reyes,Semi-Private,Discharged - SNF,10269.73,N
3390,S002251,PT-01615,03/03/2025,"March 08, 2025",5.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Reyes,ICU,Discharged - Home,"$46,530.62",N
10319,S002379,PT-00821,03-07-2025,03/13/2025,6.0,Emergency,Pulmonology,J44.1,COPD EXACERBATION,Dr. Ibrahim,Private,Discharged - Home,16597.68,N
9434,S002385,PT-02588,"March 07, 2025",03-14-2025,7.0,Urgent,Behavioral Health,F32.2,Major depressive episode,Dr. Bianchi,Private,Discharged - Home,11890.31,N
4417,S002420,PT-00385,03/08/2025,03/10/2025,2.0,Elective,Orthopedics,Z96.651,elective total knee replacement,Dr. Petrov,Private,Discharged - Home,8414.94,N
4583,S002626,PT-03739,03-14-2025,2025-03-19,5.0,Emergency,Behavioral Health,F19.20,substance use / overdose,Dr. Bianchi,Private,Discharged - SNF,10670.01,N
9198,S002668,PT-02425,2025-03-16,26-Mar-2025,10.0,Elective,Pulmonology,J18.9,Pneumonia,Dr. Osborne,Private,Home Health Care,"$17,797.89",N
8139,S002669,PT-03787,03-16-2025,"March 19, 2025",3.0,Emergency,General Surgery,K35.80,Appendicitis,Dr. Silva,Semi-Private,Discharged - Home,"$12,843.67",N
6494,S002767,PT-00765,03/19/2025,"March 27, 2025",8.0,Emergency,Pulmonology,J18.9,pneumonia,Dr. Castillo,Semi-Private,Discharged - SNF,"$19,729.83",N
5953,S002780,PT-03401,19-Mar-2025,03-25-2025,6.0,Emergency,Nephrology,N18.9,Chronic kidney disease exacerbation,Dr. Bennett,ICU,Discharged - SNF,15424.58,N
10433,S003029,PT-01059,03-26-2025,28-Mar-2025,2.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Bianchi,Ward,Discharged - Home,"$3,394.85",N
5009,S003153,PT-02523,03-30-2025,"March 31, 2025",1.0,Urgent,Cardiology,R07.9,"Chest pain, observation",Dr. Bianchi,Semi-Private,Discharged - Home,"$2,511.34",N
8209,S003249,PT-03097,02-Apr-2025,"April 08, 2025",6.0,Urgent,Cardiology,I21.9,Acute myocardial infarction,Dr. Okafor,ICU,NaN,28529.06,N
4201,S003364,PT-00162,05-Apr-2025,04-10-2025,5.0,Urgent,Internal Medicine,L03.90,Cellulitis,Dr. Mendez,Ward,NaN,12009.53,N
6028,S003441,PT-01393,"April 08, 2025","April 15, 2025",7.0,Emergency,Pulmonology,J18.9,Pneumonia,Dr. Castillo,Private,Discharged - Home,20024.36,N
8791,S003500,PT-01835,2025-04-10,04/13/2025,3.0,Emergency,Orthopedics,S72.001A,Hip fracture,Dr. Whitfield,ICU,Discharged - Home,"$13,921.01",N
7299,S003509,PT-01872,04-11-2025,14-Apr-2025,3.0,Elective,Orthopedics,Z96.651,Elective total knee replacement,Dr. Whitfield,Private,Discharged - Home,9719.06,Y
7928,S003527,PT-01047,"April 11, 2025",12-Apr-2025,1.0,Urgent,Pulmonology,J45.901,Asthma exacerbation,Dr. Ibrahim,Semi-Private,Discharged - Home,"$2,375.05",N
9711,S003685,PT-02381,17-Apr-2025,04/19/2025,2.0,Urgent,Urology,N20.0,Kidney stones,Dr. Kim,Ward,Discharged - Home,5580.38,N
3289,S003741,PT-00163,04-18-2025,2025-04-26,8.0,Emergency,Neurology,I63.9,Ischemic stroke,Dr. Reyes,Private,Transferred,39049.53,N
10608,S004027,PT-01942,28-Apr-2025,30-Apr-2025,2.0,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Ward,Discharged - Home,3767.47,N
3934,S004028,PT-00978,2025-04-29,"May 04, 2025",5.0,Emergency,Pulmonology,J11.1,INFLUENZA WITH COMPLICATIONS,Dr. Ibrahim,Private,Discharged - Home,"$13,183.55",N
9354,S004078,PT-03202,01-May-2025,2025-05-02,1.0,Emergency,Obstetrics,O80,"Vaginal delivery, uncomplicated",Dr. Larsen,Semi-Private,Discharged - Home,1891.31,N
7752,S004143,PT-04088,03-May-2025,05-05-2025,2.0,Emergency,Pulmonology,U07.1,COVID-19,Dr. Kowalski,Private,Discharged - Home,5438.03,N
10098,S004226,PT-01322,"May 07, 2025",2025-05-12,5.0,Emergency,Behavioral Health,F32.2,Major depressive episode,Dr. Chen,Private,Discharged - Home,10413.04,N
10662,S004262,PT-01726,08-May-2025,"May 13, 2025",5.0,Urgent,Gastroenterology,K92.2,GI bleed,Dr. Silva,Private,Discharged - Home,18008.63,N
1006,S004350,PT-01565,05/12/2025,16-May-2025,4.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Castillo,Semi-Private,Home Health Care,"$7,271.10",Y
10814,S004375,PT-02003,2025-05-13,2025-05-17,4.0,Emergency,Trauma,V89.2XXA,Motor vehicle accident trauma,Dr. Silva,ICU,Discharged - SNF,"$20,541.24",N
4775,S004521,PT-01521,05/19/2025,05/20/2025,1.0,Emergency,cardiology,R07.9,"Chest pain, observation",NaN,Semi-Private,Discharged - Home,1776.7,N
3708,S004599,PT-00529,23-May-2025,NaN,3.0,Urgent,Oncology,Z51.11,Chemotherapy admission,Dr. Fitzgerald,Private,Discharged - Home,13394.24,N
6602,S004659,PT-03500,"May 25, 2025",2025-05-28,NaN,Emergency,Pulmonology,J45.901,Asthma exacerbation,Dr. Osborne,Semi-Private,Discharged - Home,6340.89,N
4774,S004779,PT-00782,2025-05-29,"June 02, 2025",NaN,Emergency,Endocrinology,E11.9,Diabetes with complications,Dr. Mendez,Private,Discharged - Home,"$10,089.27",N
7300,S004780,PT-03501,"May 29, 2025",06/01/2025,3.0,Emergency,Endocrinology,E11.9,Diabetes with complications,Dr. Haddad,Semi-Private,Discharged - Home,"$7,202.33",N
10251,S004926,PT-00905,2025-06-04,2025-06-07,3.0,Emergency,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Semi-Private,Discharged - Home,"$6,231.41",N
2689,S005026,PT-03448,2025-06-08,11-Jun-2025,3.0,Emergency,INTERNAL MEDICINE,N39.0,Urinary tract infection,Dr. Voss,Ward,Discharged - Home,6573.41,N
7756,S005073,PT00937,06/09/2025,"June 14, 2025",5.0,Urgent,Behavioral Health,F32.2,Major depressive episode,Dr. Chen,Private,Discharged - Home,"$9,407.31",N
6935,S005104,PT-01313,11-Jun-2025,06/15/2025,NaN,Emergency,Neurology,I63.9,Ischemic stroke,Dr. Osei,Private,Discharged - SNF,20514.64,N
6635,S005150,PT-03958,06-12-2025,"June 14, 2025",NaN,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Okafor,Ward,Discharged - Home,"$4,635.66",N
10167,S005207,PT-00881,06/15/2025,2025-06-23,8.0,Emergency,Behavioral Health,F32.2,Major depressive episode,Dr. Chen,Semi-Private,Home Health Care,"$12,074.75",N
9855,S005249,PT-04173,2025-06-16,06/21/2025,5.0,Urgent,Cardiology,I50.9,CONGESTIVE HEART FAILURE,Dr. Bianchi,Private,Discharged - Rehab,"$16,255.24",N
3218,S005442,PT-01788,06-23-2025,25-Jun-2025,NaN,Elective,Endocrinology,E11.9,Diabetes with complications,Dr. Haddad,Private,Discharged - Home,"$5,649.41",N
6850,S005469,PT-01325,2025-06-24,2025-06-26,2.0,Urgent,UROLOGY,N20.0,Kidney stones,Dr. Voss,Semi-Private,Discharged - Home,5895.78,N
9813,S005484,PT-00180,06/25/2025,06/30/2025,5.0,Emergency,Internal Medicine,A41.9,Sepsis,Dr. Mendez,ICU,NaN,36520.98,Y
3509,S005564,PT-01632,"June 28, 2025",07/01/2025,3.0,Emergency,General Surgery,K35.80,Appendicitis,Dr. Whitfield,Private,Home Health Care,"$7,957.32",N
6997,S005591,PT03771,06-29-2025,07-02-2025,3.0,Urgent,Pulmonology,U07.1,COVID-19,Dr. Ibrahim,Private,Discharged - SNF,10208.74,N
5574,S005685,PT-02800,07/03/2025,"July 04, 2025",1.0,Urgent,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Semi-Private,Discharged - Home,"$2,283.63",N
7608,S005880,PT-03066,11-Jul-2025,"July 15, 2025",4.0,Elective,Internal Medicine,L03.90,Cellulitis,Dr. Petrov,Ward,Discharged - Home,"$8,108.42",N
5046,S005976,PT-00773,07-15-2025,"July 17, 2025",2.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Novak,Ward,Discharged - Home,"$3,990.27",N
10762,S006072,PT03221,18-Jul-2025,07-29-2025,11.0,Emergency,Neurology,I63.9,Ischemic stroke,Dr. Osei,Private,Discharged - Home,72496.4,N
9085,S006109,PT-02041,20-Jul-2025,2025-07-28,8.0,Emergency,Neurology,I63.9,ischemic stroke,Dr. Reyes,Private,Transferred,"$53,765.38",Y
10427,S006171,PT03285,2025-07-22,07-25-2025,3.0,Emergency,General Surgery,K35.80,Appendicitis,Dr. Silva,Semi-Private,Home Health Care,"$9,819.74",N
7409,S006219,PT-04083,24-Jul-2025,27-Jul-2025,3.0,Emergency,Endocrinology,E11.9,Diabetes with complications,Dr. Haddad,Private,Discharged - Home,8736.16,N
8558,S006495,PT-01524,08/04/2025,2025-08-12,8.0,Urgent,Trauma,V89.2XXA,Motor vehicle accident trauma,Dr. Kim,Private,NaN,"$44,714.79",N
10811,S006597,PT-00476,08-08-2025,"August 18, 2025",10.0,Emergency,PULMONOLOGY,U07.1,COVID-19,Dr. Voss,Semi-Private,Home Health Care,31513.51,N
10504,S006695,PT01134,"August 12, 2025","August 24, 2025",12.0,Emergency,Internal Medicine,A41.9,Sepsis,Dr. Petrov,Private,Discharged - Home,50164.39,N
8540,S006768,PT-00175,2025-08-15,21-Aug-2025,NaN,Emergency,Internal Medicine,L03.90,Cellulitis,Dr. Voss,Ward,Discharged - Home,12028.38,N
6268,S006785,PT-00463,08-16-2025,"August 19, 2025",3.0,Emergency,General Surgery,K35.80,Appendicitis,Dr. Whitfield,Semi-Private,Discharged - SNF,"$8,682.37",N
9661,S006813,PT-00226,08-17-2025,2025-08-19,2.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Okafor,Semi-Private,Home Health Care,"$4,657.71",N
5510,S006837,PT-02627,"August 18, 2025",21-Aug-2025,3.0,Emergency,General Surgery,K35.80,Appendicitis,Dr. Delgado,Private,Home Health Care,10448.38,N
3129,S006895,PT-01734,"August 20, 2025",08-21-2025,1.0,Emergency,trauma,V89.2XXA,Motor vehicle accident trauma,Dr. Kim,ICU,Discharged - Home,6870.5,N
4298,S007035,PT-02653,26-Aug-2025,01-Sep-2025,6.0,Emergency,Pulmonology,J18.9,Pneumonia,Dr. Osborne,Private,Home Health Care,11842.73,N
9846,S007200,PT02390,09/01/2025,09-03-2025,2.0,Elective,General Surgery,K81.0,Acute cholecystitis,Dr. Delgado,Semi-Private,Discharged - Home,7687.49,N
1939,S007235,PT-02326,09-02-2025,09-06-2025,4.0,Elective,Pulmonology,J11.1,Influenza with complications,Dr. Castillo,Semi-Private,Discharged - Home,"$7,253.45",N
7159,S007285,PT-00679,09-04-2025,09/10/2025,6.0,Urgent,Internal Medicine,L03.90,Cellulitis,Dr. Voss,Ward,Discharged - Home,"$15,338.29",N
10760,S007386,PT-01825,"September 07, 2025",2025-09-13,6.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Reyes,ICU,Discharged - Home,"$27,353.54",N
3931,S007456,PT-01119,09/10/2025,09/13/2025,3.0,Emergency,Nephrology,N18.9,Chronic kidney disease exacerbation,Dr. Bennett,ICU,Discharged - Home,"$7,240.57",N
7249,S007492,PT-03160,09/12/2025,2025-09-19,7.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Novak,ICU,Discharged - Rehab,"$47,934.30",N
7877,S007613,PT-04126,2025-09-17,2025-09-23,6.0,Emergency,Oncology,Z51.11,Chemotherapy admission,Dr. Fitzgerald,Private,Discharged - SNF,"$31,883.57",N
6526,S007629,PT-02342,09-17-2025,09-21-2025,4.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Bianchi,ICU,Discharged - Rehab,"$17,216.96",Y
2914,S007656,pt-00426,09-18-2025,2025-09-22,NaN,Urgent,pulmonology,J18.9,PNEUMONIA,Dr. Ibrahim,Private,Discharged - Home,"$10,307.37",N
7225,S007687,PT03892,2025-09-19,"September 21, 2025",2.0,Emergency,Behavioral Health,F19.20,Substance use / overdose,Dr. Chen,Private,Discharged - SNF,5480.05,N
9557,S007777,pt-03271,2025-09-23,"September 25, 2025",NaN,Urgent,Pulmonology,U07.1,COVID-19,Dr. Kowalski,Private,NaN,6130.52,N
5446,S007814,PT-04084,24-Sep-2025,09-25-2025,1.0,Emergency,Urology,N20.0,Kidney stones,Dr. Voss,Ward,Discharged - Home,2182.31,N
8871,S007853,PT-01540,26-Sep-2025,2025-09-28,2.0,Urgent,Cardiology,R07.9,"chest pain, observation",Dr. Reyes,Ward,Discharged - Home,"$4,232.61",N
10293,S007922,PT-02552,"September 29, 2025","October 01, 2025",2.0,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Sorensen,Ward,Discharged - Home,2757.06,N
9551,S008064,pt-02930,10/04/2025,"October 07, 2025",NaN,Urgent,Cardiology,I48.91,atrial fibrillation,Dr. Reyes,Private,Discharged - Home,6257.7,N
4870,S008090,PT-01593,2025-10-05,10/15/2025,10.0,Elective,Pulmonology,J18.9,Pneumonia,Dr. Kowalski,Semi-Private,Left AMA,"$28,022.94",N
3156,S008098,PT-00857,10/06/2025,2025-10-08,2.0,Urgent,General Surgery,K81.0,Acute cholecystitis,Dr. Silva,Private,Discharged - Home,"$8,475.32",N
10558,S008237,PT03727,10-10-2025,2025-10-14,4.0,Emergency,Pulmonology,J18.9,Pneumonia,NaN,Private,Discharged - SNF,11537.1,N
5078,S008292,PT-00442,13-Oct-2025,2025-10-18,5.0,Elective,Orthopedics,Z96.651,Elective total knee replacement,Dr. Whitfield,Semi-Private,Discharged - SNF,"$19,171.84",N
4012,S008392,PT-01350,"October 17, 2025","October 21, 2025",4.0,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Semi-Private,Discharged - Home,5067.42,N
7482,S008420,PT-00797,10/18/2025,2025-10-21,3.0,Emergency,Internal Medicine,N39.0,Urinary tract infection,Dr. Fitzgerald,Ward,Discharged - Home,4015.44,N
6620,S008563,PT-03363,10/23/2025,06-Nov-2025,14.0,Emergency,Internal Medicine,A41.9,Sepsis,Dr. Mendez,Private,Deceased,"$90,478.38",N
5722,S008630,PT-01650,2025-10-25,"October 29, 2025",4.0,Elective,Internal Medicine,N39.0,Urinary tract infection,Dr. Sorensen,Semi-Private,Discharged - Home,"$5,769.56",N
6414,S008662,PT-00013,2025-10-26,2025-10-28,2.0,Urgent,Pulmonology,U07.1,COVID-19,Dr. Castillo,Semi-Private,Discharged - Home,5271.69,N
7734,S008742,PT-03448,2025-10-29,2025-11-01,3.0,Elective,Orthopedics,Z96.641,Elective total hip replacement,Dr. Bianchi,Private,Discharged - Home,14886.07,N
6676,S008779,pt-01920,"October 31, 2025",11-04-2025,4.0,Emergency,Internal Medicine,N39.0,Urinary tract infection,Dr. Mendez,Semi-Private,Discharged - Home,6113.33,N
8927,S008810,PT-01082,11-01-2025,11/05/2025,4.0,Emergency,Pulmonology,J18.9,Pneumonia,Dr. Voss,Private,Discharged - Home,9998.04,N
5911,S008896,PT-01317,11-03-2025,2025-11-08,5.0,Emergency,Neurology,I63.9,Ischemic stroke,Dr. Silva,Private,Deceased,"$29,275.99",N
8621,S008943,PT-00848,11/05/2025,11/13/2025,8.0,Emergency,Behavioral Health,F32.2,Major depressive episode,Dr. Chen,Semi-Private,Discharged - Home,12457.77,Y
7528,S009091,PT-00104,2025-11-10,2025-11-13,3.0,Emergency,Nephrology,N18.9,Chronic kidney disease exacerbation,Dr. Abbas,Private,Discharged - Home,"$10,503.65",Yes
10347,S009210,PT-02738,"November 13, 2025","November 17, 2025",4.0,Urgent,Pulmonology,J11.1,Influenza with complications,Dr. Ibrahim,Private,NaN,8250.93,N
4199,S009254,PT-03235,15-Nov-2025,11/19/2025,4.0,Emergency,PULMONOLOGY,J45.901,Asthma exacerbation,Dr. Ibrahim,Ward,Home Health Care,8964.66,N
9197,S009702,PT-00024,11/29/2025,"November 30, 2025",1.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Kowalski,Semi-Private,Discharged - Home,2220.92,N
8109,S009708,PT-01951,29-Nov-2025,"December 02, 2025",NaN,Emergency,Behavioral Health,F32.2,Major depressive episode,Dr. Bianchi,Private,Discharged - Home,"$5,429.97",No
5409,S009832,PT-00750,03-Dec-2025,2025-12-08,5.0,Urgent,Pulmonology,J18.9,Pneumonia,Dr. Ibrahim,Semi-Private,Discharged - Home,"$14,008.44",Y
10802,S009874,PT-02533,2025-12-04,"December 11, 2025",7.0,Elective,PULMONOLOGY,J18.9,Pneumonia,Dr. Ibrahim,Semi-Private,Discharged - Home,18814.16,N
3149,S009962,PT-01674,12-06-2025,"December 10, 2025",4.0,Emergency,PULMONOLOGY,J44.1,COPD exacerbation,Dr. Osborne,Semi-Private,Discharged - Home,"$9,709.55",N
6904,S010059,PT-02523,12-09-2025,15-Dec-2025,6.0,Emergency,Pulmonology,U07.1,COVID-19,Dr. Castillo,Private,Discharged - Home,17014.74,Y
4626,S010119,PT-01863,"December 10, 2025",12-12-2025,2.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Okafor,Ward,Home Health Care,"$4,534.01",N
9971,S010159,PT-00901,"December 11, 2025",2025-12-13,2.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Ward,Discharged - Home,3649.18,N
3105,S010222,PT00796,13-Dec-2025,12/19/2025,6.0,Emergency,Cardiology,I50.9,Congestive heart failure,NaN,Private,Discharged - Home,15594.29,Y
9112,S010246,PT-02998,12/14/2025,12/21/2025,7.0,Emergency,Gastroenterology,K92.2,GI bleed,Dr. Silva,ICU,Discharged - SNF,27483.2,N
5759,S010331,PT-02998,12/16/2025,12-17-2025,1.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Novak,Semi-Private,Discharged - Home,"$2,494.24",N
8972,S010335,PT-02644,2025-12-16,2025-12-19,3.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Bianchi,Private,Discharged - Rehab,"$22,765.27",N
5853,S010362,pt-03180,12/17/2025,12/19/2025,2.0,Emergency,Pulmonology,J45.901,Asthma exacerbation,Dr. Kowalski,Semi-Private,Discharged - Home,"$4,868.12",N
7465,S010500,PT-01851,12-21-2025,"December 23, 2025",2.0,Emergency,oncology,Z51.11,Chemotherapy admission,Dr. Voss,Private,Discharged - Home,11152.64,N
8467,S010668,PT-00816,12/26/2025,2025-12-28,2.0,Emergency,UROLOGY,N20.0,Kidney stones,Dr. Choudhury,Ward,Discharged - Home,"$3,586.18",N

In [73]:
#Remove all duplicate values
hospital_stays.drop_duplicates().head(50)

,stay_id,patient_id,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis_code,diagnosis_description,attending_physician,room_type,discharge_status,total_charge_usd,readmission_within_30_days
0,S007869,01674,2025-09-26,2025-09-29,3.0,Emergency,Behavioral Health,F19.20,Substance Use / Overdose,NaN,ICU,Discharged - Home,4169.1,No
1,S000352,02670,2025-01-11,2025-01-16,5.0,Urgent,Pulmonology,J44.1,Copd Exacerbation,Voss,Semi-Private,Discharged - Home,"13,031.58",No
2,S007291,03216,2025-09-04,2025-09-06,2.0,Elective,Cardiology,R07.9,"Chest Pain, Observation",Novak,Semi-Private,Discharged - Home,"3,988.81",No
3,S002933,02352,2025-03-23,2025-03-26,NaN,Urgent,Urology,N20.0,Kidney Stones,Kim,Ward,Discharged - Home,"5,865.28",No
4,S007038,02472,2025-08-26,2025-08-31,5.0,Emergency,Endocrinology,E11.9,Diabetes With Complications,Patel,Semi-Private,Discharged - SNF,14533.41,No
5,S009678,02493,2025-11-28,2025-11-30,NaN,Urgent,Oncology,Z51.11,Chemotherapy Admission,Fitzgerald,Private,Discharged - SNF,10536.61,No
6,S004525,01595,2025-05-19,2025-05-24,5.0,Elective,General Surgery,K81.0,Acute Cholecystitis,Delgado,Private,Home Health Care,17936.7,No
7,S006779,01010,2025-08-15,2025-08-17,2.0,Emergency,Cardiology,R07.9,"Chest Pain, Observation",Bianchi,Semi-Private,Discharged - Home,"4,035.01",No
8,S002679,03836,2025-03-16,2025-03-18,2.0,Emergency,Pulmonology,J11.1,Influenza With Complications,Osborne,Private,Discharged - Home,"4,890.55",No
9,S006853,00288,2025-08-19,2025-08-22,3.0,Urgent,Urology,N20.0,Kidney Stones,Kim,Ward,Home Health Care,"5,951.77",No
10,S009139,02969,2025-11-11,2025-11-15,4.0,Urgent,Pulmonology,J11.1,Influenza With Complications,Voss,Semi-Private,Discharged - Home,8199.89,No
11,S007256,03421,2025-09-02,2025-09-07,5.0,Elective,Orthopedics,Z96.641,Elective Total Hip Replacement,Petrov,Semi-Private,Discharged - Home,19900.49,No
12,S006664,02586,2025-08-11,2025-08-16,5.0,Urgent,Pulmonology,J11.1,Influenza With Complications,Osborne,Private,NaN,11663.16,No
13,S006852,03608,2025-08-19,2025-08-21,2.0,Emergency,General Surgery,K81.0,Acute Cholecystitis,Whitfield,Private,Discharged - Home,"5,476.93",No
14,S003609,01784,2025-04-14,2025-04-16,2.0,Emergency,Behavioral Health,F19.20,Substance Use / Overdose,Chen,ICU,Discharged - Home,"3,642.94",No
15,S002496,01623,2025-03-10,2025-03-16,6.0,Emergency,Cardiology,I21.9,Acute Myocardial Infarction,Bianchi,Private,Discharged - Rehab,28656.88,Yes
16,S002391,00111,2025-03-07,2025-03-13,6.0,Emergency,Pulmonology,J18.9,Pneumonia,Castillo,Private,Discharged - Home,11475.38,No
17,S005754,03306,2025-07-06,2025-07-07,1.0,Emergency,Cardiology,R07.9,"Chest Pain, Observation",Reyes,Semi-Private,Discharged - Home,"1,584.61",No
18,S002341,03871,2025-03-05,2025-03-08,3.0,Emergency,Internal Medicine,L03.90,Cellulitis,Sorensen,Semi-Private,Discharged - Home,"5,980.90",Yes
19,S006012,04013,2025-07-16,2025-07-20,4.0,Urgent,Endocrinology,E11.9,Diabetes With Complications,Mendez,Private,Discharged - Home,6800.4,Yes
20,S000685,03851,2025-01-20,2025-01-23,3.0,Urgent,Pulmonology,J18.9,Pneumonia,Ibrahim,Semi-Private,Discharged - SNF,8463.89,No
21,S006762,00619,2025-08-15,2025-08-20,5.0,Urgent,General Surgery,K81.0,Acute Cholecystitis,Whitfield,Private,Home Health Care,"12,702.60",No
22,S006422,01525,2025-08-01,2025-08-05,4.0,Urgent,Cardiology,I48.91,Atrial Fibrillation,Reyes,Semi-Private,NaN,"12,816.24",No
23,S002406,02935,2025-03-08,2025-03-10,2.0,Emergency,Obstetrics,O14.90,Preeclampsia,Larsen,ICU,Discharged - Home,"6,792.49",No
24,S005239,00666,2025-06-16,2025-06-19,3.0,Emergency,Cardiology,I48.91,Atrial Fibrillation,Novak,Semi-Private,Home Health Care,9175.59,No
25,S008001,02610,2025-10-02,2025-10-04,2.0,Elective,Oncology,Z51.11,Chemotherapy Admission,Voss,Private,Discharged - Home,"10,598.38",No
26,S007186,03773,2025-08-31,2025-09-01,1.0,Elective,Internal Medicine,N39.0,Urinary Tract Infection,Mendez,Semi-Private,Discharged - Home,2051.34,No
27,S005854,02713,2025-07-10,2025-07-16,6.0,Emergency,Trauma,V89.2XXA,Motor Vehicle Accident Trauma,Mendez,ICU,Discharged - Home,23874.13,No
28,S007469,01170,2025-09-11,2025-09-14,3.0,Emergency,General Surgery,K81.0,Acute Cholecystitis,Whitfield,Semi-Private,Discharged - Home,9629.17,Yes
29,S007009,02034,2025-08-25,2025-09-02,8.0,Emergency,Neurology,I63.9,Ischemic Stroke,Silva,ICU,Discharged - Home,"52,622.33",No
30,S001686,01922,2025-02-16,2025-02-18,2.0,Elective,Pulmonology,J45.901,Asthma Exacerbation,Kowalski,Ward,Home Health Care,4497.05,No
31,S002884,00915,2025-03-22,2025-03-25,3.0,Urgent,Pulmonology,U07.1,Covid-19,Voss,Semi-Private,NaN,"9,690.55",No
32,S008144,03502,2025-10-07,2025-10-12,5.0,Emergency,Cardiology,I21.9,Acute Myocardial Infarction,Okafo,Private,Transferred,"34,487.89",No
33,S008285,04155,2025-10-13,2025-10-24,11.0,Urgent,Cardiology,I50.9,Congestive Heart Failure,Okafo,ICU,Discharged - Rehab,"44,121.88",No
34,S003447,01317,2025-04-09,2025-04-13,NaN,Urgent,Internal Medicine,L03.90,Cellulitis,Mendez,Ward,Discharged - Home,"7,846.32",No
35,S006696,02521,2025-08-12,2025-08-13,1.0,Elective,Cardiology,R07.9,"Chest Pain, Observation",Reyes,Semi-Private,Discharged - Home,"2,298.57",No
36,S003309,01199,2025-04-04,2025-04-09,5.0,Elective,Internal Medicine,N39.0,Urinary Tract Infection,Mendez,Semi-Private,Discharged - Home,10730.36,No
37,S002306,03661,2025-03-05,2025-03-07,2.0,Urgent,Pulmonology,J18.9,Pneumonia,Kowalski,Private,Discharged - Home,3758.73,No
38,S003117,03354,2025-03-29,2025-04-02,4.0,Urgent,Pulmonology,J44.1,Copd Exacerbation,Ibrahim,Private,Left AMA,8690.29,No
39,S003992,03514,2025-04-27,2025-05-01,4.0,Elective,Pulmonology,U07.1,Covid-19,Castillo,Private,Discharged - Home,11126.04,No
40,S006701,03976,2025-08-12,2025-08-21,9.0,Emergency,Endocrinology,E11.9,Diabetes With Complications,Haddad,Semi-Private,Discharged - Home,16501.25,No
41,S005755,00776,2025-07-06,2025-07-09,3.0,Elective,Orthopedics,Z96.651,Elective Total Knee Replacement,Whitfield,Private,Discharged - Home,"13,098.57",Yes
42,S009331,03775,2025-11-17,2025-11-20,NaN,Urgent,Internal Medicine,N39.0,Urinary Tract Infection,Voss,Ward,Discharged - Home,6923.17,No
43,S009744,00868,2025-11-30,2025-12-02,2.0,Urgent,Cardiology,R07.9,"Chest Pain, Observation",Reyes,Ward,Discharged - Home,4829.67,No
44,S005915,02591,2025-07-13,2025-07-18,NaN,Emergency,Nephrology,N18.9,Chronic Kidney Disease Exacerbation,Sorensen,Private,Discharged - Home,19210.72,No
45,S006573,02076,2025-08-06,2025-08-07,1.0,Emergency,Urology,N20.0,Kidney Stones,Voss,Ward,Home Health Care,"2,313.78",No
46,S005419,04086,2025-06-22,2025-06-24,2.0,Elective,Orthopedics,Z96.651,Elective Total Knee Replacement,Whitfield,Private,Discharged - Home,"7,289.17",No
47,S000651,02371,2025-01-19,2025-01-24,5.0,Emergency,Pulmonology,J11.1,Influenza With Complications,Kowalski,Private,NaN,"8,442.58",No
48,S008392,01350,2025-10-17,2025-10-21,4.0,Urgent,Internal Medicine,N39.0,Urinary Tract Infection,Voss,Semi-Private,Discharged - Home,5067.42,No
49,S009451,00091,2025-11-20,2025-11-25,5.0,Emergency,Cardiology,I48.91,Atrial Fibrillation,Okafo,Private,Discharged - Home,17223.3,No

In [45]:
#Edit patient_id column to remove the prefix PT before each value
hospital_stays['patient_id']=hospital_stays['patient_id'].str.strip('PT-')
hospital_stays['patient_id']=hospital_stays['patient_id'].str.strip('pt-')
hospital_stays.head(50)

,stay_id,patient_id,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis_code,diagnosis_description,attending_physician,room_type,discharge_status,total_charge_usd,readmission_within_30_days
0,S007869,01674,2025-09-26,2025-09-29,3.0,Emergency,Behavioral Health,F19.20,Substance use / overdose,NaN,ICU,Discharged - Home,4169.1,N
1,S000352,02670,01/11/2025,16-Jan-2025,5.0,Urgent,PULMONOLOGY,J44.1,COPD exacerbation,Dr. Voss,Semi-Private,Discharged - Home,"$13,031.58",N
2,S007291,03216,09/04/2025,2025-09-06,2.0,Elective,Cardiology,R07.9,"Chest pain, observation",Dr. Novak,Semi-Private,Discharged - Home,"$3,988.81",N
3,S002933,02352,03-23-2025,03-26-2025,NaN,Urgent,UROLOGY,N20.0,Kidney stones,Dr. Kim,Ward,Discharged - Home,"$5,865.28",N
4,S007038,02472,08-26-2025,08/31/2025,5.0,Emergency,Endocrinology,E11.9,Diabetes with complications,Dr. Patel,Semi-Private,Discharged - SNF,14533.41,N
5,S009678,02493,2025-11-28,30-Nov-2025,NaN,Urgent,Oncology,Z51.11,Chemotherapy admission,Dr. Fitzgerald,Private,Discharged - SNF,10536.61,N
6,S004525,01595,"May 19, 2025",05-24-2025,5.0,Elective,General Surgery,K81.0,Acute cholecystitis,Dr. Delgado,Private,Home Health Care,17936.7,N
7,S006779,01010,15-Aug-2025,17-Aug-2025,2.0,Emergency,Cardiology,R07.9,"CHEST PAIN, OBSERVATION",Dr. Bianchi,Semi-Private,Discharged - Home,"$4,035.01",N
8,S002679,03836,03/16/2025,03/18/2025,2.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Osborne,Private,Discharged - Home,"$4,890.55",N
9,S006853,00288,08-19-2025,08-22-2025,3.0,Urgent,Urology,N20.0,Kidney stones,Dr. Kim,Ward,Home Health Care,"$5,951.77",N
10,S009139,02969,11-11-2025,15-Nov-2025,4.0,Urgent,Pulmonology,J11.1,INFLUENZA WITH COMPLICATIONS,Dr. Voss,Semi-Private,Discharged - Home,8199.89,N
11,S007256,03421,"September 02, 2025",07-Sep-2025,5.0,Elective,Orthopedics,Z96.641,Elective total hip replacement,Dr. Petrov,Semi-Private,Discharged - Home,19900.49,N
12,S006664,02586,2025-08-11,16-Aug-2025,5.0,Urgent,PULMONOLOGY,J11.1,Influenza with complications,Dr. Osborne,Private,NaN,11663.16,N
13,S006852,03608,08-19-2025,"August 21, 2025",2.0,Emergency,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Private,Discharged - Home,"$5,476.93",N
14,S003609,01784,14-Apr-2025,16-Apr-2025,2.0,Emergency,Behavioral Health,F19.20,Substance use / overdose,Dr. Chen,ICU,Discharged - Home,"$3,642.94",N
15,S002496,01623,10-Mar-2025,03/16/2025,6.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Bianchi,Private,Discharged - Rehab,28656.88,Yes
16,S002391,00111,03/07/2025,13-Mar-2025,6.0,Emergency,pulmonology,J18.9,Pneumonia,Dr. Castillo,Private,Discharged - Home,11475.38,N
17,S005754,03306,07-06-2025,07-07-2025,1.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Semi-Private,Discharged - Home,"$1,584.61",N
18,S002341,03871,2025-03-05,"March 08, 2025",3.0,Emergency,Internal Medicine,L03.90,Cellulitis,Dr. Sorensen,Semi-Private,Discharged - Home,"$5,980.90",Y
19,S006012,04013,16-Jul-2025,2025-07-20,4.0,Urgent,Endocrinology,E11.9,Diabetes with complications,Dr. Mendez,Private,Discharged - Home,6800.4,y
20,S000685,03851,2025-01-20,01/23/2025,3.0,Urgent,Pulmonology,J18.9,Pneumonia,Dr. Ibrahim,Semi-Private,Discharged - SNF,8463.89,N
21,S006762,00619,"August 15, 2025",20-Aug-2025,5.0,Urgent,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Private,Home Health Care,"$12,702.60",N
22,S006422,01525,2025-08-01,"August 05, 2025",4.0,Urgent,Cardiology,I48.91,Atrial fibrillation,Dr. Reyes,Semi-Private,NaN,"$12,816.24",N
23,S002406,02935,03-08-2025,2025-03-10,2.0,Emergency,Obstetrics,O14.90,Preeclampsia,Dr. Larsen,ICU,Discharged - Home,"$6,792.49",N
24,S005239,00666,06-16-2025,2025-06-19,3.0,Emergency,Cardiology,I48.91,Atrial fibrillation,Dr. Novak,Semi-Private,Home Health Care,9175.59,N
25,S008001,02610,"October 02, 2025",10/04/2025,2.0,Elective,Oncology,Z51.11,Chemotherapy admission,Dr. Voss,Private,Discharged - Home,"$10,598.38",N
26,S007186,03773,08/31/2025,2025-09-01,1.0,Elective,INTERNAL MEDICINE,N39.0,urinary tract infection,Dr. Mendez,Semi-Private,Discharged - Home,2051.34,N
27,S005854,02713,07/10/2025,2025-07-16,6.0,Emergency,TRAUMA,V89.2XXA,Motor vehicle accident trauma,Dr. Mendez,ICU,Discharged - Home,23874.13,N
28,S007469,01170,11-Sep-2025,14-Sep-2025,3.0,Emergency,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Semi-Private,Discharged - Home,9629.17,Yes
29,S007009,02034,25-Aug-2025,2025-09-02,8.0,Emergency,Neurology,I63.9,Ischemic stroke,Dr. Silva,ICU,Discharged - Home,"$52,622.33",N
30,S001686,01922,16-Feb-2025,2025-02-18,2.0,Elective,Pulmonology,J45.901,asthma exacerbation,Dr. Kowalski,Ward,Home Health Care,4497.05,N
31,S002884,00915,22-Mar-2025,03-25-2025,3.0,Urgent,Pulmonology,U07.1,COVID-19,Dr. Voss,Semi-Private,NaN,"$9,690.55",N
32,S008144,03502,07-Oct-2025,10/12/2025,5.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Okafor,Private,Transferred,"$34,487.89",N
33,S008285,04155,2025-10-13,24-Oct-2025,11.0,Urgent,Cardiology,I50.9,Congestive heart failure,Dr. Okafor,ICU,Discharged - Rehab,"$44,121.88",N
34,S003447,01317,04/09/2025,04-13-2025,NaN,Urgent,Internal Medicine,L03.90,Cellulitis,Dr. Mendez,Ward,Discharged - Home,"$7,846.32",N
35,S006696,02521,12-Aug-2025,"August 13, 2025",1.0,Elective,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Semi-Private,Discharged - Home,"$2,298.57",N
36,S003309,01199,04-04-2025,04/09/2025,5.0,Elective,Internal Medicine,N39.0,Urinary tract infection,Dr. Mendez,Semi-Private,Discharged - Home,10730.36,N
37,S002306,03661,2025-03-05,"March 07, 2025",2.0,Urgent,Pulmonology,J18.9,Pneumonia,Dr. Kowalski,Private,Discharged - Home,3758.73,N
38,S003117,03354,03/29/2025,02-Apr-2025,4.0,Urgent,Pulmonology,J44.1,COPD exacerbation,Dr. Ibrahim,Private,Left AMA,8690.29,N
39,S003992,03514,04-27-2025,"May 01, 2025",4.0,Elective,Pulmonology,U07.1,COVID-19,Dr. Castillo,Private,Discharged - Home,11126.04,N
40,S006701,03976,08/12/2025,2025-08-21,9.0,Emergency,endocrinology,E11.9,Diabetes with complications,Dr. Haddad,Semi-Private,Discharged - Home,16501.25,N
41,S005755,00776,07/06/2025,"July 09, 2025",3.0,Elective,Orthopedics,Z96.651,Elective total knee replacement,Dr. Whitfield,Private,Discharged - Home,"$13,098.57",Y
42,S009331,03775,11-17-2025,"November 20, 2025",NaN,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Ward,Discharged - Home,6923.17,N
43,S009744,00868,11-30-2025,12/02/2025,2.0,Urgent,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Ward,Discharged - Home,4829.67,N
44,S005915,02591,"July 13, 2025",07/18/2025,NaN,Emergency,Nephrology,N18.9,chronic kidney disease exacerbation,Dr. Sorensen,Private,Discharged - Home,19210.72,N
45,S006573,02076,"August 06, 2025",08/07/2025,1.0,Emergency,Urology,N20.0,Kidney stones,Dr. Voss,Ward,Home Health Care,"$2,313.78",N
46,S005419,04086,06/22/2025,06-24-2025,2.0,Elective,Orthopedics,Z96.651,elective total knee replacement,Dr. Whitfield,Private,Discharged - Home,"$7,289.17",N
47,S000651,02371,2025-01-19,24-Jan-2025,5.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Kowalski,Private,NaN,"$8,442.58",N
48,S008392,01350,"October 17, 2025","October 21, 2025",4.0,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Semi-Private,Discharged - Home,5067.42,N
49,S009451,00091,11/20/2025,11/25/2025,5.0,Emergency,Cardiology,I48.91,Atrial fibrillation,Dr. Okafor,Private,Discharged - Home,17223.3,N

In [46]:
#Edit admission_date column to ensure consistent date formatting
hospital_stays['admission_date']=pd.to_datetime(hospital_stays['admission_date']).dt.date
hospital_stays.head(50)

,stay_id,patient_id,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis_code,diagnosis_description,attending_physician,room_type,discharge_status,total_charge_usd,readmission_within_30_days
0,S007869,01674,2025-09-26,2025-09-29,3.0,Emergency,Behavioral Health,F19.20,Substance use / overdose,NaN,ICU,Discharged - Home,4169.1,N
1,S000352,02670,2025-01-11,16-Jan-2025,5.0,Urgent,PULMONOLOGY,J44.1,COPD exacerbation,Dr. Voss,Semi-Private,Discharged - Home,"$13,031.58",N
2,S007291,03216,2025-09-04,2025-09-06,2.0,Elective,Cardiology,R07.9,"Chest pain, observation",Dr. Novak,Semi-Private,Discharged - Home,"$3,988.81",N
3,S002933,02352,2025-03-23,03-26-2025,NaN,Urgent,UROLOGY,N20.0,Kidney stones,Dr. Kim,Ward,Discharged - Home,"$5,865.28",N
4,S007038,02472,2025-08-26,08/31/2025,5.0,Emergency,Endocrinology,E11.9,Diabetes with complications,Dr. Patel,Semi-Private,Discharged - SNF,14533.41,N
5,S009678,02493,2025-11-28,30-Nov-2025,NaN,Urgent,Oncology,Z51.11,Chemotherapy admission,Dr. Fitzgerald,Private,Discharged - SNF,10536.61,N
6,S004525,01595,2025-05-19,05-24-2025,5.0,Elective,General Surgery,K81.0,Acute cholecystitis,Dr. Delgado,Private,Home Health Care,17936.7,N
7,S006779,01010,2025-08-15,17-Aug-2025,2.0,Emergency,Cardiology,R07.9,"CHEST PAIN, OBSERVATION",Dr. Bianchi,Semi-Private,Discharged - Home,"$4,035.01",N
8,S002679,03836,2025-03-16,03/18/2025,2.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Osborne,Private,Discharged - Home,"$4,890.55",N
9,S006853,00288,2025-08-19,08-22-2025,3.0,Urgent,Urology,N20.0,Kidney stones,Dr. Kim,Ward,Home Health Care,"$5,951.77",N
10,S009139,02969,2025-11-11,15-Nov-2025,4.0,Urgent,Pulmonology,J11.1,INFLUENZA WITH COMPLICATIONS,Dr. Voss,Semi-Private,Discharged - Home,8199.89,N
11,S007256,03421,2025-09-02,07-Sep-2025,5.0,Elective,Orthopedics,Z96.641,Elective total hip replacement,Dr. Petrov,Semi-Private,Discharged - Home,19900.49,N
12,S006664,02586,2025-08-11,16-Aug-2025,5.0,Urgent,PULMONOLOGY,J11.1,Influenza with complications,Dr. Osborne,Private,NaN,11663.16,N
13,S006852,03608,2025-08-19,"August 21, 2025",2.0,Emergency,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Private,Discharged - Home,"$5,476.93",N
14,S003609,01784,2025-04-14,16-Apr-2025,2.0,Emergency,Behavioral Health,F19.20,Substance use / overdose,Dr. Chen,ICU,Discharged - Home,"$3,642.94",N
15,S002496,01623,2025-03-10,03/16/2025,6.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Bianchi,Private,Discharged - Rehab,28656.88,Yes
16,S002391,00111,2025-03-07,13-Mar-2025,6.0,Emergency,pulmonology,J18.9,Pneumonia,Dr. Castillo,Private,Discharged - Home,11475.38,N
17,S005754,03306,2025-07-06,07-07-2025,1.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Semi-Private,Discharged - Home,"$1,584.61",N
18,S002341,03871,2025-03-05,"March 08, 2025",3.0,Emergency,Internal Medicine,L03.90,Cellulitis,Dr. Sorensen,Semi-Private,Discharged - Home,"$5,980.90",Y
19,S006012,04013,2025-07-16,2025-07-20,4.0,Urgent,Endocrinology,E11.9,Diabetes with complications,Dr. Mendez,Private,Discharged - Home,6800.4,y
20,S000685,03851,2025-01-20,01/23/2025,3.0,Urgent,Pulmonology,J18.9,Pneumonia,Dr. Ibrahim,Semi-Private,Discharged - SNF,8463.89,N
21,S006762,00619,2025-08-15,20-Aug-2025,5.0,Urgent,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Private,Home Health Care,"$12,702.60",N
22,S006422,01525,2025-08-01,"August 05, 2025",4.0,Urgent,Cardiology,I48.91,Atrial fibrillation,Dr. Reyes,Semi-Private,NaN,"$12,816.24",N
23,S002406,02935,2025-03-08,2025-03-10,2.0,Emergency,Obstetrics,O14.90,Preeclampsia,Dr. Larsen,ICU,Discharged - Home,"$6,792.49",N
24,S005239,00666,2025-06-16,2025-06-19,3.0,Emergency,Cardiology,I48.91,Atrial fibrillation,Dr. Novak,Semi-Private,Home Health Care,9175.59,N
25,S008001,02610,2025-10-02,10/04/2025,2.0,Elective,Oncology,Z51.11,Chemotherapy admission,Dr. Voss,Private,Discharged - Home,"$10,598.38",N
26,S007186,03773,2025-08-31,2025-09-01,1.0,Elective,INTERNAL MEDICINE,N39.0,urinary tract infection,Dr. Mendez,Semi-Private,Discharged - Home,2051.34,N
27,S005854,02713,2025-07-10,2025-07-16,6.0,Emergency,TRAUMA,V89.2XXA,Motor vehicle accident trauma,Dr. Mendez,ICU,Discharged - Home,23874.13,N
28,S007469,01170,2025-09-11,14-Sep-2025,3.0,Emergency,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Semi-Private,Discharged - Home,9629.17,Yes
29,S007009,02034,2025-08-25,2025-09-02,8.0,Emergency,Neurology,I63.9,Ischemic stroke,Dr. Silva,ICU,Discharged - Home,"$52,622.33",N
30,S001686,01922,2025-02-16,2025-02-18,2.0,Elective,Pulmonology,J45.901,asthma exacerbation,Dr. Kowalski,Ward,Home Health Care,4497.05,N
31,S002884,00915,2025-03-22,03-25-2025,3.0,Urgent,Pulmonology,U07.1,COVID-19,Dr. Voss,Semi-Private,NaN,"$9,690.55",N
32,S008144,03502,2025-10-07,10/12/2025,5.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Okafor,Private,Transferred,"$34,487.89",N
33,S008285,04155,2025-10-13,24-Oct-2025,11.0,Urgent,Cardiology,I50.9,Congestive heart failure,Dr. Okafor,ICU,Discharged - Rehab,"$44,121.88",N
34,S003447,01317,2025-04-09,04-13-2025,NaN,Urgent,Internal Medicine,L03.90,Cellulitis,Dr. Mendez,Ward,Discharged - Home,"$7,846.32",N
35,S006696,02521,2025-08-12,"August 13, 2025",1.0,Elective,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Semi-Private,Discharged - Home,"$2,298.57",N
36,S003309,01199,2025-04-04,04/09/2025,5.0,Elective,Internal Medicine,N39.0,Urinary tract infection,Dr. Mendez,Semi-Private,Discharged - Home,10730.36,N
37,S002306,03661,2025-03-05,"March 07, 2025",2.0,Urgent,Pulmonology,J18.9,Pneumonia,Dr. Kowalski,Private,Discharged - Home,3758.73,N
38,S003117,03354,2025-03-29,02-Apr-2025,4.0,Urgent,Pulmonology,J44.1,COPD exacerbation,Dr. Ibrahim,Private,Left AMA,8690.29,N
39,S003992,03514,2025-04-27,"May 01, 2025",4.0,Elective,Pulmonology,U07.1,COVID-19,Dr. Castillo,Private,Discharged - Home,11126.04,N
40,S006701,03976,2025-08-12,2025-08-21,9.0,Emergency,endocrinology,E11.9,Diabetes with complications,Dr. Haddad,Semi-Private,Discharged - Home,16501.25,N
41,S005755,00776,2025-07-06,"July 09, 2025",3.0,Elective,Orthopedics,Z96.651,Elective total knee replacement,Dr. Whitfield,Private,Discharged - Home,"$13,098.57",Y
42,S009331,03775,2025-11-17,"November 20, 2025",NaN,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Ward,Discharged - Home,6923.17,N
43,S009744,00868,2025-11-30,12/02/2025,2.0,Urgent,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Ward,Discharged - Home,4829.67,N
44,S005915,02591,2025-07-13,07/18/2025,NaN,Emergency,Nephrology,N18.9,chronic kidney disease exacerbation,Dr. Sorensen,Private,Discharged - Home,19210.72,N
45,S006573,02076,2025-08-06,08/07/2025,1.0,Emergency,Urology,N20.0,Kidney stones,Dr. Voss,Ward,Home Health Care,"$2,313.78",N
46,S005419,04086,2025-06-22,06-24-2025,2.0,Elective,Orthopedics,Z96.651,elective total knee replacement,Dr. Whitfield,Private,Discharged - Home,"$7,289.17",N
47,S000651,02371,2025-01-19,24-Jan-2025,5.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Kowalski,Private,NaN,"$8,442.58",N
48,S008392,01350,2025-10-17,"October 21, 2025",4.0,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Semi-Private,Discharged - Home,5067.42,N
49,S009451,00091,2025-11-20,11/25/2025,5.0,Emergency,Cardiology,I48.91,Atrial fibrillation,Dr. Okafor,Private,Discharged - Home,17223.3,N

In [47]:
#Clean discharge_date column for consistent date formatting
hospital_stays['discharge_date']=pd.to_datetime(hospital_stays['discharge_date']).dt.date
hospital_stays.head(50)

,stay_id,patient_id,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis_code,diagnosis_description,attending_physician,room_type,discharge_status,total_charge_usd,readmission_within_30_days
0,S007869,01674,2025-09-26,2025-09-29,3.0,Emergency,Behavioral Health,F19.20,Substance use / overdose,NaN,ICU,Discharged - Home,4169.1,N
1,S000352,02670,2025-01-11,2025-01-16,5.0,Urgent,PULMONOLOGY,J44.1,COPD exacerbation,Dr. Voss,Semi-Private,Discharged - Home,"$13,031.58",N
2,S007291,03216,2025-09-04,2025-09-06,2.0,Elective,Cardiology,R07.9,"Chest pain, observation",Dr. Novak,Semi-Private,Discharged - Home,"$3,988.81",N
3,S002933,02352,2025-03-23,2025-03-26,NaN,Urgent,UROLOGY,N20.0,Kidney stones,Dr. Kim,Ward,Discharged - Home,"$5,865.28",N
4,S007038,02472,2025-08-26,2025-08-31,5.0,Emergency,Endocrinology,E11.9,Diabetes with complications,Dr. Patel,Semi-Private,Discharged - SNF,14533.41,N
5,S009678,02493,2025-11-28,2025-11-30,NaN,Urgent,Oncology,Z51.11,Chemotherapy admission,Dr. Fitzgerald,Private,Discharged - SNF,10536.61,N
6,S004525,01595,2025-05-19,2025-05-24,5.0,Elective,General Surgery,K81.0,Acute cholecystitis,Dr. Delgado,Private,Home Health Care,17936.7,N
7,S006779,01010,2025-08-15,2025-08-17,2.0,Emergency,Cardiology,R07.9,"CHEST PAIN, OBSERVATION",Dr. Bianchi,Semi-Private,Discharged - Home,"$4,035.01",N
8,S002679,03836,2025-03-16,2025-03-18,2.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Osborne,Private,Discharged - Home,"$4,890.55",N
9,S006853,00288,2025-08-19,2025-08-22,3.0,Urgent,Urology,N20.0,Kidney stones,Dr. Kim,Ward,Home Health Care,"$5,951.77",N
10,S009139,02969,2025-11-11,2025-11-15,4.0,Urgent,Pulmonology,J11.1,INFLUENZA WITH COMPLICATIONS,Dr. Voss,Semi-Private,Discharged - Home,8199.89,N
11,S007256,03421,2025-09-02,2025-09-07,5.0,Elective,Orthopedics,Z96.641,Elective total hip replacement,Dr. Petrov,Semi-Private,Discharged - Home,19900.49,N
12,S006664,02586,2025-08-11,2025-08-16,5.0,Urgent,PULMONOLOGY,J11.1,Influenza with complications,Dr. Osborne,Private,NaN,11663.16,N
13,S006852,03608,2025-08-19,2025-08-21,2.0,Emergency,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Private,Discharged - Home,"$5,476.93",N
14,S003609,01784,2025-04-14,2025-04-16,2.0,Emergency,Behavioral Health,F19.20,Substance use / overdose,Dr. Chen,ICU,Discharged - Home,"$3,642.94",N
15,S002496,01623,2025-03-10,2025-03-16,6.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Bianchi,Private,Discharged - Rehab,28656.88,Yes
16,S002391,00111,2025-03-07,2025-03-13,6.0,Emergency,pulmonology,J18.9,Pneumonia,Dr. Castillo,Private,Discharged - Home,11475.38,N
17,S005754,03306,2025-07-06,2025-07-07,1.0,Emergency,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Semi-Private,Discharged - Home,"$1,584.61",N
18,S002341,03871,2025-03-05,2025-03-08,3.0,Emergency,Internal Medicine,L03.90,Cellulitis,Dr. Sorensen,Semi-Private,Discharged - Home,"$5,980.90",Y
19,S006012,04013,2025-07-16,2025-07-20,4.0,Urgent,Endocrinology,E11.9,Diabetes with complications,Dr. Mendez,Private,Discharged - Home,6800.4,y
20,S000685,03851,2025-01-20,2025-01-23,3.0,Urgent,Pulmonology,J18.9,Pneumonia,Dr. Ibrahim,Semi-Private,Discharged - SNF,8463.89,N
21,S006762,00619,2025-08-15,2025-08-20,5.0,Urgent,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Private,Home Health Care,"$12,702.60",N
22,S006422,01525,2025-08-01,2025-08-05,4.0,Urgent,Cardiology,I48.91,Atrial fibrillation,Dr. Reyes,Semi-Private,NaN,"$12,816.24",N
23,S002406,02935,2025-03-08,2025-03-10,2.0,Emergency,Obstetrics,O14.90,Preeclampsia,Dr. Larsen,ICU,Discharged - Home,"$6,792.49",N
24,S005239,00666,2025-06-16,2025-06-19,3.0,Emergency,Cardiology,I48.91,Atrial fibrillation,Dr. Novak,Semi-Private,Home Health Care,9175.59,N
25,S008001,02610,2025-10-02,2025-10-04,2.0,Elective,Oncology,Z51.11,Chemotherapy admission,Dr. Voss,Private,Discharged - Home,"$10,598.38",N
26,S007186,03773,2025-08-31,2025-09-01,1.0,Elective,INTERNAL MEDICINE,N39.0,urinary tract infection,Dr. Mendez,Semi-Private,Discharged - Home,2051.34,N
27,S005854,02713,2025-07-10,2025-07-16,6.0,Emergency,TRAUMA,V89.2XXA,Motor vehicle accident trauma,Dr. Mendez,ICU,Discharged - Home,23874.13,N
28,S007469,01170,2025-09-11,2025-09-14,3.0,Emergency,General Surgery,K81.0,Acute cholecystitis,Dr. Whitfield,Semi-Private,Discharged - Home,9629.17,Yes
29,S007009,02034,2025-08-25,2025-09-02,8.0,Emergency,Neurology,I63.9,Ischemic stroke,Dr. Silva,ICU,Discharged - Home,"$52,622.33",N
30,S001686,01922,2025-02-16,2025-02-18,2.0,Elective,Pulmonology,J45.901,asthma exacerbation,Dr. Kowalski,Ward,Home Health Care,4497.05,N
31,S002884,00915,2025-03-22,2025-03-25,3.0,Urgent,Pulmonology,U07.1,COVID-19,Dr. Voss,Semi-Private,NaN,"$9,690.55",N
32,S008144,03502,2025-10-07,2025-10-12,5.0,Emergency,Cardiology,I21.9,Acute myocardial infarction,Dr. Okafor,Private,Transferred,"$34,487.89",N
33,S008285,04155,2025-10-13,2025-10-24,11.0,Urgent,Cardiology,I50.9,Congestive heart failure,Dr. Okafor,ICU,Discharged - Rehab,"$44,121.88",N
34,S003447,01317,2025-04-09,2025-04-13,NaN,Urgent,Internal Medicine,L03.90,Cellulitis,Dr. Mendez,Ward,Discharged - Home,"$7,846.32",N
35,S006696,02521,2025-08-12,2025-08-13,1.0,Elective,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Semi-Private,Discharged - Home,"$2,298.57",N
36,S003309,01199,2025-04-04,2025-04-09,5.0,Elective,Internal Medicine,N39.0,Urinary tract infection,Dr. Mendez,Semi-Private,Discharged - Home,10730.36,N
37,S002306,03661,2025-03-05,2025-03-07,2.0,Urgent,Pulmonology,J18.9,Pneumonia,Dr. Kowalski,Private,Discharged - Home,3758.73,N
38,S003117,03354,2025-03-29,2025-04-02,4.0,Urgent,Pulmonology,J44.1,COPD exacerbation,Dr. Ibrahim,Private,Left AMA,8690.29,N
39,S003992,03514,2025-04-27,2025-05-01,4.0,Elective,Pulmonology,U07.1,COVID-19,Dr. Castillo,Private,Discharged - Home,11126.04,N
40,S006701,03976,2025-08-12,2025-08-21,9.0,Emergency,endocrinology,E11.9,Diabetes with complications,Dr. Haddad,Semi-Private,Discharged - Home,16501.25,N
41,S005755,00776,2025-07-06,2025-07-09,3.0,Elective,Orthopedics,Z96.651,Elective total knee replacement,Dr. Whitfield,Private,Discharged - Home,"$13,098.57",Y
42,S009331,03775,2025-11-17,2025-11-20,NaN,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Ward,Discharged - Home,6923.17,N
43,S009744,00868,2025-11-30,2025-12-02,2.0,Urgent,Cardiology,R07.9,"Chest pain, observation",Dr. Reyes,Ward,Discharged - Home,4829.67,N
44,S005915,02591,2025-07-13,2025-07-18,NaN,Emergency,Nephrology,N18.9,chronic kidney disease exacerbation,Dr. Sorensen,Private,Discharged - Home,19210.72,N
45,S006573,02076,2025-08-06,2025-08-07,1.0,Emergency,Urology,N20.0,Kidney stones,Dr. Voss,Ward,Home Health Care,"$2,313.78",N
46,S005419,04086,2025-06-22,2025-06-24,2.0,Elective,Orthopedics,Z96.651,elective total knee replacement,Dr. Whitfield,Private,Discharged - Home,"$7,289.17",N
47,S000651,02371,2025-01-19,2025-01-24,5.0,Emergency,Pulmonology,J11.1,Influenza with complications,Dr. Kowalski,Private,NaN,"$8,442.58",N
48,S008392,01350,2025-10-17,2025-10-21,4.0,Urgent,Internal Medicine,N39.0,Urinary tract infection,Dr. Voss,Semi-Private,Discharged - Home,5067.42,N
49,S009451,00091,2025-11-20,2025-11-25,5.0,Emergency,Cardiology,I48.91,Atrial fibrillation,Dr. Okafor,Private,Discharged - Home,17223.3,N

In [48]:
#Inspect values in admission_type column and determine data errors
hospital_stays['admission_type'].value_counts()

Emergency    6675
Urgent       2655
Elective     1600
Name: admission_type, dtype: int64

In [49]:
#Inspect department column to identify data inconsistencies
hospital_stays['department'].value_counts()

#Ensure proper capitalization and remove trailing whitespaces 
hospital_stays['department']=hospital_stays['department'].str.title()
hospital_stays['department']=hospital_stays['department'].str.strip()

hospital_stays['department'].value_counts()

Pulmonology          2875
Internal Medicine    1962
Cardiology           1750
Orthopedics           647
General Surgery       640
Behavioral Health     541
Endocrinology         402
Gastroenterology      378
Urology               370
Neurology             350
Trauma                305
Nephrology            251
Oncology              233
Obstetrics            207
Pediatrics             19
Name: department, dtype: int64

In [50]:
hospital_stays['diagnosis_description'].value_counts()

#Ensure proper capitalization across all diagnosis descriptions
hospital_stays['diagnosis_description']=hospital_stays['diagnosis_description'].str.title()
hospital_stays['diagnosis_description'].value_counts()

Pneumonia                               804
Urinary Tract Infection                 781
Influenza With Complications            713
Cellulitis                              619
Chest Pain, Observation                 569
Sepsis                                  562
Covid-19                                513
Asthma Exacerbation                     443
Congestive Heart Failure                432
Acute Myocardial Infarction             423
Diabetes With Complications             402
Copd Exacerbation                       402
Gi Bleed                                378
Ischemic Stroke                         350
Acute Cholecystitis                     342
Atrial Fibrillation                     326
Major Depressive Episode                320
Motor Vehicle Accident Trauma           305
Kidney Stones                           300
Appendicitis                            298
Elective Total Knee Replacement         274
Chronic Kidney Disease Exacerbation     251
Chemotherapy Admission                  233
Substance Use / Overdose                221
Elective Total Hip Replacement          196
Hip Fracture                            177
Vaginal Delivery, Uncomplicated         111
Benign Prostatic Hyperplasia Surgery     70
Cesarean Delivery                        67
Preeclampsia                             29
Bronchiolitis (Pediatric)                17
Neonatal Jaundice Observation             2
Name: diagnosis_description, dtype: int64

In [51]:
hospital_stays['room_type'].value_counts()

Private         4032
Semi-Private    3896
ICU             1518
Ward            1484
Name: room_type, dtype: int64

In [52]:
hospital_stays['attending_physician']=hospital_stays['attending_physician'].str.strip('Dr.')
hospital_stays.head(50)

,stay_id,patient_id,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis_code,diagnosis_description,attending_physician,room_type,discharge_status,total_charge_usd,readmission_within_30_days
0,S007869,01674,2025-09-26,2025-09-29,3.0,Emergency,Behavioral Health,F19.20,Substance Use / Overdose,NaN,ICU,Discharged - Home,4169.1,N
1,S000352,02670,2025-01-11,2025-01-16,5.0,Urgent,Pulmonology,J44.1,Copd Exacerbation,Voss,Semi-Private,Discharged - Home,"$13,031.58",N
2,S007291,03216,2025-09-04,2025-09-06,2.0,Elective,Cardiology,R07.9,"Chest Pain, Observation",Novak,Semi-Private,Discharged - Home,"$3,988.81",N
3,S002933,02352,2025-03-23,2025-03-26,NaN,Urgent,Urology,N20.0,Kidney Stones,Kim,Ward,Discharged - Home,"$5,865.28",N
4,S007038,02472,2025-08-26,2025-08-31,5.0,Emergency,Endocrinology,E11.9,Diabetes With Complications,Patel,Semi-Private,Discharged - SNF,14533.41,N
5,S009678,02493,2025-11-28,2025-11-30,NaN,Urgent,Oncology,Z51.11,Chemotherapy Admission,Fitzgerald,Private,Discharged - SNF,10536.61,N
6,S004525,01595,2025-05-19,2025-05-24,5.0,Elective,General Surgery,K81.0,Acute Cholecystitis,Delgado,Private,Home Health Care,17936.7,N
7,S006779,01010,2025-08-15,2025-08-17,2.0,Emergency,Cardiology,R07.9,"Chest Pain, Observation",Bianchi,Semi-Private,Discharged - Home,"$4,035.01",N
8,S002679,03836,2025-03-16,2025-03-18,2.0,Emergency,Pulmonology,J11.1,Influenza With Complications,Osborne,Private,Discharged - Home,"$4,890.55",N
9,S006853,00288,2025-08-19,2025-08-22,3.0,Urgent,Urology,N20.0,Kidney Stones,Kim,Ward,Home Health Care,"$5,951.77",N
10,S009139,02969,2025-11-11,2025-11-15,4.0,Urgent,Pulmonology,J11.1,Influenza With Complications,Voss,Semi-Private,Discharged - Home,8199.89,N
11,S007256,03421,2025-09-02,2025-09-07,5.0,Elective,Orthopedics,Z96.641,Elective Total Hip Replacement,Petrov,Semi-Private,Discharged - Home,19900.49,N
12,S006664,02586,2025-08-11,2025-08-16,5.0,Urgent,Pulmonology,J11.1,Influenza With Complications,Osborne,Private,NaN,11663.16,N
13,S006852,03608,2025-08-19,2025-08-21,2.0,Emergency,General Surgery,K81.0,Acute Cholecystitis,Whitfield,Private,Discharged - Home,"$5,476.93",N
14,S003609,01784,2025-04-14,2025-04-16,2.0,Emergency,Behavioral Health,F19.20,Substance Use / Overdose,Chen,ICU,Discharged - Home,"$3,642.94",N
15,S002496,01623,2025-03-10,2025-03-16,6.0,Emergency,Cardiology,I21.9,Acute Myocardial Infarction,Bianchi,Private,Discharged - Rehab,28656.88,Yes
16,S002391,00111,2025-03-07,2025-03-13,6.0,Emergency,Pulmonology,J18.9,Pneumonia,Castillo,Private,Discharged - Home,11475.38,N
17,S005754,03306,2025-07-06,2025-07-07,1.0,Emergency,Cardiology,R07.9,"Chest Pain, Observation",Reyes,Semi-Private,Discharged - Home,"$1,584.61",N
18,S002341,03871,2025-03-05,2025-03-08,3.0,Emergency,Internal Medicine,L03.90,Cellulitis,Sorensen,Semi-Private,Discharged - Home,"$5,980.90",Y
19,S006012,04013,2025-07-16,2025-07-20,4.0,Urgent,Endocrinology,E11.9,Diabetes With Complications,Mendez,Private,Discharged - Home,6800.4,y
20,S000685,03851,2025-01-20,2025-01-23,3.0,Urgent,Pulmonology,J18.9,Pneumonia,Ibrahim,Semi-Private,Discharged - SNF,8463.89,N
21,S006762,00619,2025-08-15,2025-08-20,5.0,Urgent,General Surgery,K81.0,Acute Cholecystitis,Whitfield,Private,Home Health Care,"$12,702.60",N
22,S006422,01525,2025-08-01,2025-08-05,4.0,Urgent,Cardiology,I48.91,Atrial Fibrillation,Reyes,Semi-Private,NaN,"$12,816.24",N
23,S002406,02935,2025-03-08,2025-03-10,2.0,Emergency,Obstetrics,O14.90,Preeclampsia,Larsen,ICU,Discharged - Home,"$6,792.49",N
24,S005239,00666,2025-06-16,2025-06-19,3.0,Emergency,Cardiology,I48.91,Atrial Fibrillation,Novak,Semi-Private,Home Health Care,9175.59,N
25,S008001,02610,2025-10-02,2025-10-04,2.0,Elective,Oncology,Z51.11,Chemotherapy Admission,Voss,Private,Discharged - Home,"$10,598.38",N
26,S007186,03773,2025-08-31,2025-09-01,1.0,Elective,Internal Medicine,N39.0,Urinary Tract Infection,Mendez,Semi-Private,Discharged - Home,2051.34,N
27,S005854,02713,2025-07-10,2025-07-16,6.0,Emergency,Trauma,V89.2XXA,Motor Vehicle Accident Trauma,Mendez,ICU,Discharged - Home,23874.13,N
28,S007469,01170,2025-09-11,2025-09-14,3.0,Emergency,General Surgery,K81.0,Acute Cholecystitis,Whitfield,Semi-Private,Discharged - Home,9629.17,Yes
29,S007009,02034,2025-08-25,2025-09-02,8.0,Emergency,Neurology,I63.9,Ischemic Stroke,Silva,ICU,Discharged - Home,"$52,622.33",N
30,S001686,01922,2025-02-16,2025-02-18,2.0,Elective,Pulmonology,J45.901,Asthma Exacerbation,Kowalski,Ward,Home Health Care,4497.05,N
31,S002884,00915,2025-03-22,2025-03-25,3.0,Urgent,Pulmonology,U07.1,Covid-19,Voss,Semi-Private,NaN,"$9,690.55",N
32,S008144,03502,2025-10-07,2025-10-12,5.0,Emergency,Cardiology,I21.9,Acute Myocardial Infarction,Okafo,Private,Transferred,"$34,487.89",N
33,S008285,04155,2025-10-13,2025-10-24,11.0,Urgent,Cardiology,I50.9,Congestive Heart Failure,Okafo,ICU,Discharged - Rehab,"$44,121.88",N
34,S003447,01317,2025-04-09,2025-04-13,NaN,Urgent,Internal Medicine,L03.90,Cellulitis,Mendez,Ward,Discharged - Home,"$7,846.32",N
35,S006696,02521,2025-08-12,2025-08-13,1.0,Elective,Cardiology,R07.9,"Chest Pain, Observation",Reyes,Semi-Private,Discharged - Home,"$2,298.57",N
36,S003309,01199,2025-04-04,2025-04-09,5.0,Elective,Internal Medicine,N39.0,Urinary Tract Infection,Mendez,Semi-Private,Discharged - Home,10730.36,N
37,S002306,03661,2025-03-05,2025-03-07,2.0,Urgent,Pulmonology,J18.9,Pneumonia,Kowalski,Private,Discharged - Home,3758.73,N
38,S003117,03354,2025-03-29,2025-04-02,4.0,Urgent,Pulmonology,J44.1,Copd Exacerbation,Ibrahim,Private,Left AMA,8690.29,N
39,S003992,03514,2025-04-27,2025-05-01,4.0,Elective,Pulmonology,U07.1,Covid-19,Castillo,Private,Discharged - Home,11126.04,N
40,S006701,03976,2025-08-12,2025-08-21,9.0,Emergency,Endocrinology,E11.9,Diabetes With Complications,Haddad,Semi-Private,Discharged - Home,16501.25,N
41,S005755,00776,2025-07-06,2025-07-09,3.0,Elective,Orthopedics,Z96.651,Elective Total Knee Replacement,Whitfield,Private,Discharged - Home,"$13,098.57",Y
42,S009331,03775,2025-11-17,2025-11-20,NaN,Urgent,Internal Medicine,N39.0,Urinary Tract Infection,Voss,Ward,Discharged - Home,6923.17,N
43,S009744,00868,2025-11-30,2025-12-02,2.0,Urgent,Cardiology,R07.9,"Chest Pain, Observation",Reyes,Ward,Discharged - Home,4829.67,N
44,S005915,02591,2025-07-13,2025-07-18,NaN,Emergency,Nephrology,N18.9,Chronic Kidney Disease Exacerbation,Sorensen,Private,Discharged - Home,19210.72,N
45,S006573,02076,2025-08-06,2025-08-07,1.0,Emergency,Urology,N20.0,Kidney Stones,Voss,Ward,Home Health Care,"$2,313.78",N
46,S005419,04086,2025-06-22,2025-06-24,2.0,Elective,Orthopedics,Z96.651,Elective Total Knee Replacement,Whitfield,Private,Discharged - Home,"$7,289.17",N
47,S000651,02371,2025-01-19,2025-01-24,5.0,Emergency,Pulmonology,J11.1,Influenza With Complications,Kowalski,Private,NaN,"$8,442.58",N
48,S008392,01350,2025-10-17,2025-10-21,4.0,Urgent,Internal Medicine,N39.0,Urinary Tract Infection,Voss,Semi-Private,Discharged - Home,5067.42,N
49,S009451,00091,2025-11-20,2025-11-25,5.0,Emergency,Cardiology,I48.91,Atrial Fibrillation,Okafo,Private,Discharged - Home,17223.3,N

In [53]:
hospital_stays['readmission_within_30_days'].value_counts()

hospital_stays['readmission_within_30_days']=hospital_stays['readmission_within_30_days'].replace({'Y':'Yes','N':'No','y':'Yes','n':'No'})
hospital_stays['readmission_within_30_days'].value_counts()

No     9247
Yes    1683
Name: readmission_within_30_days, dtype: int64

In [54]:
hospital_stays['total_charge_usd']=hospital_stays['total_charge_usd'].str.strip('$')
hospital_stays['total_charge_usd']=hospital_stays['total_charge_usd'].str.strip(',')
hospital_stays['total_charge_usd'].value_counts().head(50)

13394.24     2
46,530.62    2
4,534.01     2
52,632.73    2
20024.36     2
12428.5      2
7,271.10     2
27,524.41    2
2,494.24     2
3,586.18     2
17,018.24    2
6,107.13     2
16,255.24    2
7,202.33     2
9,407.31     2
10,503.65    2
2,511.34     2
6,060.13     2
4015.44      2
14886.07     2
8964.66      2
4,657.71     2
8736.16      2
7,240.57     2
5480.05      2
9719.06      2
15,230.72    2
6113.33      2
4,710.68     2
8,108.42     2
2757.06      2
31,883.57    2
8414.94      2
31513.51     2
5522.04      2
29,275.99    2
7,836.58     2
53,765.38    2
28529.06     2
44,714.79    2
20514.64     2
36520.98     2
4,232.61     2
6130.52      2
2220.92      2
15594.29     2
2908.08      2
3,394.85     2
8,741.28     2
11890.31     2
Name: total_charge_usd, dtype: int64

In [55]:
hospital_stays.head(50)

,stay_id,patient_id,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis_code,diagnosis_description,attending_physician,room_type,discharge_status,total_charge_usd,readmission_within_30_days
0,S007869,01674,2025-09-26,2025-09-29,3.0,Emergency,Behavioral Health,F19.20,Substance Use / Overdose,NaN,ICU,Discharged - Home,4169.1,No
1,S000352,02670,2025-01-11,2025-01-16,5.0,Urgent,Pulmonology,J44.1,Copd Exacerbation,Voss,Semi-Private,Discharged - Home,"13,031.58",No
2,S007291,03216,2025-09-04,2025-09-06,2.0,Elective,Cardiology,R07.9,"Chest Pain, Observation",Novak,Semi-Private,Discharged - Home,"3,988.81",No
3,S002933,02352,2025-03-23,2025-03-26,NaN,Urgent,Urology,N20.0,Kidney Stones,Kim,Ward,Discharged - Home,"5,865.28",No
4,S007038,02472,2025-08-26,2025-08-31,5.0,Emergency,Endocrinology,E11.9,Diabetes With Complications,Patel,Semi-Private,Discharged - SNF,14533.41,No
5,S009678,02493,2025-11-28,2025-11-30,NaN,Urgent,Oncology,Z51.11,Chemotherapy Admission,Fitzgerald,Private,Discharged - SNF,10536.61,No
6,S004525,01595,2025-05-19,2025-05-24,5.0,Elective,General Surgery,K81.0,Acute Cholecystitis,Delgado,Private,Home Health Care,17936.7,No
7,S006779,01010,2025-08-15,2025-08-17,2.0,Emergency,Cardiology,R07.9,"Chest Pain, Observation",Bianchi,Semi-Private,Discharged - Home,"4,035.01",No
8,S002679,03836,2025-03-16,2025-03-18,2.0,Emergency,Pulmonology,J11.1,Influenza With Complications,Osborne,Private,Discharged - Home,"4,890.55",No
9,S006853,00288,2025-08-19,2025-08-22,3.0,Urgent,Urology,N20.0,Kidney Stones,Kim,Ward,Home Health Care,"5,951.77",No
10,S009139,02969,2025-11-11,2025-11-15,4.0,Urgent,Pulmonology,J11.1,Influenza With Complications,Voss,Semi-Private,Discharged - Home,8199.89,No
11,S007256,03421,2025-09-02,2025-09-07,5.0,Elective,Orthopedics,Z96.641,Elective Total Hip Replacement,Petrov,Semi-Private,Discharged - Home,19900.49,No
12,S006664,02586,2025-08-11,2025-08-16,5.0,Urgent,Pulmonology,J11.1,Influenza With Complications,Osborne,Private,NaN,11663.16,No
13,S006852,03608,2025-08-19,2025-08-21,2.0,Emergency,General Surgery,K81.0,Acute Cholecystitis,Whitfield,Private,Discharged - Home,"5,476.93",No
14,S003609,01784,2025-04-14,2025-04-16,2.0,Emergency,Behavioral Health,F19.20,Substance Use / Overdose,Chen,ICU,Discharged - Home,"3,642.94",No
15,S002496,01623,2025-03-10,2025-03-16,6.0,Emergency,Cardiology,I21.9,Acute Myocardial Infarction,Bianchi,Private,Discharged - Rehab,28656.88,Yes
16,S002391,00111,2025-03-07,2025-03-13,6.0,Emergency,Pulmonology,J18.9,Pneumonia,Castillo,Private,Discharged - Home,11475.38,No
17,S005754,03306,2025-07-06,2025-07-07,1.0,Emergency,Cardiology,R07.9,"Chest Pain, Observation",Reyes,Semi-Private,Discharged - Home,"1,584.61",No
18,S002341,03871,2025-03-05,2025-03-08,3.0,Emergency,Internal Medicine,L03.90,Cellulitis,Sorensen,Semi-Private,Discharged - Home,"5,980.90",Yes
19,S006012,04013,2025-07-16,2025-07-20,4.0,Urgent,Endocrinology,E11.9,Diabetes With Complications,Mendez,Private,Discharged - Home,6800.4,Yes
20,S000685,03851,2025-01-20,2025-01-23,3.0,Urgent,Pulmonology,J18.9,Pneumonia,Ibrahim,Semi-Private,Discharged - SNF,8463.89,No
21,S006762,00619,2025-08-15,2025-08-20,5.0,Urgent,General Surgery,K81.0,Acute Cholecystitis,Whitfield,Private,Home Health Care,"12,702.60",No
22,S006422,01525,2025-08-01,2025-08-05,4.0,Urgent,Cardiology,I48.91,Atrial Fibrillation,Reyes,Semi-Private,NaN,"12,816.24",No
23,S002406,02935,2025-03-08,2025-03-10,2.0,Emergency,Obstetrics,O14.90,Preeclampsia,Larsen,ICU,Discharged - Home,"6,792.49",No
24,S005239,00666,2025-06-16,2025-06-19,3.0,Emergency,Cardiology,I48.91,Atrial Fibrillation,Novak,Semi-Private,Home Health Care,9175.59,No
25,S008001,02610,2025-10-02,2025-10-04,2.0,Elective,Oncology,Z51.11,Chemotherapy Admission,Voss,Private,Discharged - Home,"10,598.38",No
26,S007186,03773,2025-08-31,2025-09-01,1.0,Elective,Internal Medicine,N39.0,Urinary Tract Infection,Mendez,Semi-Private,Discharged - Home,2051.34,No
27,S005854,02713,2025-07-10,2025-07-16,6.0,Emergency,Trauma,V89.2XXA,Motor Vehicle Accident Trauma,Mendez,ICU,Discharged - Home,23874.13,No
28,S007469,01170,2025-09-11,2025-09-14,3.0,Emergency,General Surgery,K81.0,Acute Cholecystitis,Whitfield,Semi-Private,Discharged - Home,9629.17,Yes
29,S007009,02034,2025-08-25,2025-09-02,8.0,Emergency,Neurology,I63.9,Ischemic Stroke,Silva,ICU,Discharged - Home,"52,622.33",No
30,S001686,01922,2025-02-16,2025-02-18,2.0,Elective,Pulmonology,J45.901,Asthma Exacerbation,Kowalski,Ward,Home Health Care,4497.05,No
31,S002884,00915,2025-03-22,2025-03-25,3.0,Urgent,Pulmonology,U07.1,Covid-19,Voss,Semi-Private,NaN,"9,690.55",No
32,S008144,03502,2025-10-07,2025-10-12,5.0,Emergency,Cardiology,I21.9,Acute Myocardial Infarction,Okafo,Private,Transferred,"34,487.89",No
33,S008285,04155,2025-10-13,2025-10-24,11.0,Urgent,Cardiology,I50.9,Congestive Heart Failure,Okafo,ICU,Discharged - Rehab,"44,121.88",No
34,S003447,01317,2025-04-09,2025-04-13,NaN,Urgent,Internal Medicine,L03.90,Cellulitis,Mendez,Ward,Discharged - Home,"7,846.32",No
35,S006696,02521,2025-08-12,2025-08-13,1.0,Elective,Cardiology,R07.9,"Chest Pain, Observation",Reyes,Semi-Private,Discharged - Home,"2,298.57",No
36,S003309,01199,2025-04-04,2025-04-09,5.0,Elective,Internal Medicine,N39.0,Urinary Tract Infection,Mendez,Semi-Private,Discharged - Home,10730.36,No
37,S002306,03661,2025-03-05,2025-03-07,2.0,Urgent,Pulmonology,J18.9,Pneumonia,Kowalski,Private,Discharged - Home,3758.73,No
38,S003117,03354,2025-03-29,2025-04-02,4.0,Urgent,Pulmonology,J44.1,Copd Exacerbation,Ibrahim,Private,Left AMA,8690.29,No
39,S003992,03514,2025-04-27,2025-05-01,4.0,Elective,Pulmonology,U07.1,Covid-19,Castillo,Private,Discharged - Home,11126.04,No
40,S006701,03976,2025-08-12,2025-08-21,9.0,Emergency,Endocrinology,E11.9,Diabetes With Complications,Haddad,Semi-Private,Discharged - Home,16501.25,No
41,S005755,00776,2025-07-06,2025-07-09,3.0,Elective,Orthopedics,Z96.651,Elective Total Knee Replacement,Whitfield,Private,Discharged - Home,"13,098.57",Yes
42,S009331,03775,2025-11-17,2025-11-20,NaN,Urgent,Internal Medicine,N39.0,Urinary Tract Infection,Voss,Ward,Discharged - Home,6923.17,No
43,S009744,00868,2025-11-30,2025-12-02,2.0,Urgent,Cardiology,R07.9,"Chest Pain, Observation",Reyes,Ward,Discharged - Home,4829.67,No
44,S005915,02591,2025-07-13,2025-07-18,NaN,Emergency,Nephrology,N18.9,Chronic Kidney Disease Exacerbation,Sorensen,Private,Discharged - Home,19210.72,No
45,S006573,02076,2025-08-06,2025-08-07,1.0,Emergency,Urology,N20.0,Kidney Stones,Voss,Ward,Home Health Care,"2,313.78",No
46,S005419,04086,2025-06-22,2025-06-24,2.0,Elective,Orthopedics,Z96.651,Elective Total Knee Replacement,Whitfield,Private,Discharged - Home,"7,289.17",No
47,S000651,02371,2025-01-19,2025-01-24,5.0,Emergency,Pulmonology,J11.1,Influenza With Complications,Kowalski,Private,NaN,"8,442.58",No
48,S008392,01350,2025-10-17,2025-10-21,4.0,Urgent,Internal Medicine,N39.0,Urinary Tract Infection,Voss,Semi-Private,Discharged - Home,5067.42,No
49,S009451,00091,2025-11-20,2025-11-25,5.0,Emergency,Cardiology,I48.91,Atrial Fibrillation,Okafo,Private,Discharged - Home,17223.3,No

In [56]:
hospital_stays_cleaned=hospital_stays.to_csv('~/Desktop/hospital_stays_cleaned.csv')

In [57]:
patients=pd.read_csv('/Users/aaronless/Desktop/Data Analysis Porfolio Projects/Other/Hospital Stays/Original CSVs/patients.csv')
patients.head(50)

,patient_id,first_name,last_name,date_of_birth,gender,blood_type,state,zip_code,insurance_provider,phone,registration_date,chronic_condition_flag
0,PT00984,Sharon,Hall,09-Dec-2013,F,A+,TX,25865.0,UnitedHealthcare,670-712-7399,"March 11, 2022",N
1,PT-01865,Victoria,Williams,11-26-1938,Female,O+,IL,89911.0,Tricare,+11438335180,07-17-2020,N
2,PT-00032,Amy,Johnson,1947-06-19,f,A+,NJ,56848.0,Medicaid,4797990275,2015-09-26,Y
3,PT-02473,Sarah,Garcia,13-Oct-1976,female,O+,CA,55898.0,Self-Pay,+16974954932,"May 20, 2013",N
4,PT-03804,Amy,Johnson,29-May-2008,Female,O+,TX,60856.0,Humana,678-881-2019,02/20/2018,N
5,PT-03251,Donna,Campbell,1975-03-16,f,AB+,FL,24158.0,Cigna,893.838.0922,12/14/2016,N
6,PT-01064,Brandon,Flores,"March 10, 1982",MALE,O+,IL,80514.0,Cigna,(978) 548-3893,"November 06, 2021",N
7,PT-02447,Linda,Sanchez,"February 04, 2007",F,O-,IL,65850.0,Humana,788-549-6822,2018-04-27,N
8,PT-00965,Nathan,Wilson,"August 20, 2016",male,NaN,NJ,20299.0,UnitedHealthcare,997-997-5281,10-22-2022,N
9,PT-02952,Helen,Garcia,2000-08-09,Female,AB+,NY,48926.0,Aetna,881-566-8040,2012-09-16,N
10,PT-02658,Joseph,Scott,08-May-1943,m,A+,CA,54955.0,UnitedHealthcare,864-646-0041,15-Apr-2022,N
11,PT-00704,Jerry,Wright,08/31/1943,Male,B+,PA,63089.0,Cigna,570.420.0455,2012-10-02,N
12,PT-00186,Rachel,Taylor,01-12-1950,FEMALE,O+,CA,98478.0,Aetna,9627927756,04-19-2010,Y
13,PT-01849,Brenda,Harris,12/22/1932,Female,B-,NY,93461.0,Aetna,+14264223116,12-Aug-2022,N
14,PT-02547,Betty,Walker,12-May-1966,f,O+,CT,40995.0,Cigna,447-186-3693,09-Mar-2012,N
15,PT-00389,Kimberly,Flores,"January 23, 1944",female,NaN,IL,94547.0,Self-Pay,4418780280,02/25/2012,Y
16,PT-02118,Edward,Smith,18-Dec-1979,male,O+,OH,34859.0,Cigna,(834) 697-4330,02/03/2019,N
17,PT-03845,Katherine,Ramirez,1950-08-11,F,O+,MA,20008.0,Aetna,0758240931,01/30/2017,Y
18,PT-00129,Sarah,Gonzalez,03-26-1943,Female,AB-,TX,44925.0,Humana,(196) 839-6197,"October 26, 2016",N
19,PT-03285,Michelle,Moore,1997-12-30,FEMALE,O+,PA,96281.0,Tricare,062.884.2126,2015-02-28,N
20,PT-04044,Christine,Walker,02-12-2007,f,B+,CA,28365.0,Medicare,(501) 725-7449,21-Jul-2024,N
21,PT-01589,Janet,Lee,01/31/1961,female,O+,FL,13234.0,Medicare,421.666.7466,09/11/2015,N
22,PT-01556,Elizabeth,Scott,21-Jan-1942,F,O+,CT,89567.0,Kaiser Permanente,+18445952760,09/13/2020,N
23,PT-01439,Peter,WALKER,1955-04-13,male,B+,FL,96056.0,Kaiser Permanente,+15345266346,10/31/2011,N
24,PT-03614,Walter,Smith,09-Dec-1985,M,A+,FL,17411.0,Humana,574.879.9949,2019-01-03,N
25,PT-03127,Donald,Martin,2001-04-21,MALE,O+,NY,68949.0,Self-Pay,+19555805815,07-22-2010,N
26,PT-00999,Olivia,Ramirez,06-Sep-2003,female,A+,MA,49408.0,Self-Pay,823-171-3782,"January 12, 2010",N
27,PT-02270,James,Rodriguez,08-24-1980,m,O+,OH,38906.0,Medicare,+18645775770,2012-08-20,N
28,PT-00818,Samantha,Moore,14-Aug-2022,F,O-,FL,20900.0,Kaiser Permanente,NaN,"June 16, 2012",N
29,PT-00694,Jerry,Moore,12-21-1990,Male,O+,CA,94486.0,Medicare,1959903845,13-Sep-2011,N
30,PT-01336,Susan,Harris,06-17-1966,F,A+,IL,87741.0,Tricare,NaN,2013-04-22,N
31,PT-02818,Margaret,Diaz,1974-04-17,female,B+,OH,17817.0,Medicare,639.234.3391,12/02/2021,N
32,PT-03237,Jennifer,Smith,13-May-1937,F,B+,NY,61160.0,Medicaid,784.561.0722,2011-06-30,N
33,PT-01161,Rebecca,Martinez,1969-08-12,FEMALE,O+,CT,45854.0,Tricare,8784511163,2022-11-29,N
34,PT-02477,Carlos,Ramirez,06-19-2014,M,NaN,MA,51441.0,Medicare,531-561-1401,"September 05, 2014",N
35,PT-02662,Joyce,Campbell,02-08-2009,FEMALE,B-,IL,80907.0,Aetna,+13253632264,15-Sep-2022,N
36,PT-01213,Dennis,Williams,07/14/2000,male,A+,IL,36900.0,Tricare,4391980720,26-Jun-2023,Y
37,PT-03407,Melissa,Garcia,23-Dec-1980,Female,B+,TX,74348.0,Self-Pay,+18272328773,18-Dec-2020,N
38,PT-01754,Dennis,Brown,"March 10, 1970",m,O+,OH,47934.0,Humana,+14634823120,2016-01-29,Y
39,PT-00906,Edward,Baker,12/01/1953,Male,O-,FL,65796.0,Humana,(041) 324-7451,2024-09-09,Y
40,PT-00401,Brenda,Brown,01-14-1945,Female,O+,IL,78063.0,Self-Pay,5274955943,06-27-2022,N
41,pt-04008,Margaret,Lewis,"September 02, 1960",Female,O-,NJ,55543.0,Blue Cross Blue Shield,614.013.9900,"January 15, 2017",N
42,PT-00227,Kimberly,Williams,1942-12-13,female,O+,NY,68388.0,Self-Pay,969.914.1099,02-19-2017,N
43,PT-03511,Patricia,King,04/04/1968,f,A+,OH,71538.0,Aetna,1349687952,09-30-2015,N
44,PT-01935,Brandon,Edwards,12/21/1945,MALE,O-,CA,81341.0,Self-Pay,8235286524,2023-03-10,N
45,PT-01747,Jonathan,Torres,10-04-1936,m,AB+,CT,14688.0,Medicaid,5977021934,2011-05-13,N
46,PT-00779,Ryan,Hernandez,10/05/1932,Male,O+,CA,92549.0,Aetna,(429) 812-5443,19-Feb-2018,N
47,PT-00950,George,Nelson,08/26/1981,M,A+,CT,30553.0,Blue Cross Blue Shield,0936956068,"March 22, 2024",N
48,PT-03316,David,Flores,31-May-1991,m,O+,CA,63747.0,UnitedHealthcare,(417) 971-5101,28-Oct-2011,Y
49,PT-00721,Jennifer,Jackson,"March 26, 1966",Female,A+,TX,29475.0,Aetna,(950) 801-2174,"August 05, 2014",Y

In [58]:
patients['gender'].value_counts()

patients['gender']=patients['gender'].str.upper()
patients['gender'].value_counts()

patients['gender']=patients['gender'].replace({'MALE':'M','FEMALE':'F'})
patients['gender'].value_counts()

F    1883
M    1816
Name: gender, dtype: int64

In [59]:
duplicates=patients.duplicated(subset='patient_id')
patients[duplicates]

,patient_id,first_name,last_name,date_of_birth,gender,blood_type,state,zip_code,insurance_provider,phone,registration_date,chronic_condition_flag
262,PT-04044,Christine,Walker,02-12-2007,F,B+,CA,28365.0,Medicare,(501) 725-7449,21-Jul-2024,N
619,PT-03235,Joan,Thompson,11/21/2010,F,B+,TX,21057.0,Cigna,NaN,06-29-2014,N
856,PT-00895,Emma,Garcia,"November 03, 2014",F,A+,CT,99634.0,Medicaid,+14408594582,05/23/2015,N
1307,PT-03167,Nicholas,Jackson,2000-12-05,M,O+,MA,24657.0,Humana,(900) 132-8111,"August 27, 2016",N
1456,PT-00186,Rachel,Taylor,01-12-1950,F,O+,CA,98478.0,Aetna,9627927756,04-19-2010,Y
1460,PT-03294,Elizabeth,Martinez,1968-10-04,F,O-,NJ,85974.0,Humana,NaN,"October 17, 2011",N
1480,PT-03264,Scott,Moore,"November 14, 1935",M,O+,PA,41395.0,Aetna,(900) 828-0281,2022-10-14,N
1604,PT-02001,Justin,Walker,2003-09-12,M,B+,NJ,91705.0,Aetna,3026967699,11-Oct-2011,N
1634,PT-02870,Timothy,Wilson,03/21/1962,M,A+,TX,15304.0,UnitedHealthcare,4573767930,2022-08-06,N
1830,PT-03746,Jose,Jones,04-16-2019,M,A+,FL,91558.0,Humana,1781675293,18-Jul-2021,Y
1839,PT-03281,Dorothy,Johnson,26-Jun-1997,F,A+,OH,36316.0,Tricare,961-631-7275,12/12/2019,N
1920,PT-04138,Kyle,Walker,1931-07-09,M,AB+,TX,73503.0,Kaiser Permanente,+17280551596,03/26/2017,Y
1958,PT-00435,Ronald,Parker,07-30-2016,M,O+,NY,29773.0,Humana,4072765369,03/12/2016,N
1963,PT-00553,Nicholas,Phillips,"March 18, 2002",M,A+,CT,25585.0,Blue Cross Blue Shield,(157) 663-8018,06/05/2024,N
2111,PT-02189,Walter,Morris,06/18/1940,M,O+,NJ,67083.0,UnitedHealthcare,(649) 287-8046,08-05-2021,N
2217,PT-02953,Melissa,Young,"April 08, 1956",F,A+,MA,13705.0,Cigna,+16852630183,"September 20, 2013",N
2226,PT-03123,Gregory,Hernandez,12/24/1947,M,O+,NJ,NaN,Self-Pay,NaN,24-Apr-2014,N
2247,PT-00711,Joseph,Baker,1974-05-03,M,O-,PA,71277.0,Tricare,+16285530536,02-16-2018,N
2318,PT-00426,Jason,Davis,2017-11-16,M,O+,MA,79686.0,Tricare,7078799037,"January 22, 2010",N
2367,PT-00713,Jose,Brown,14-Jun-1949,M,O+,FL,46062.0,Aetna,4322273733,11-30-2020,Y
2374,PT-00691,Samuel,Miller,1931-04-01,M,B+,CT,46255.0,Aetna,082.698.6257,24-Dec-2015,N
2433,PT-02626,Dorothy,Green,07-29-1995,F,O+,OH,14734.0,Medicaid,+19816633793,"September 29, 2020",N
2436,PT-03604,Richard,Moore,"September 15, 1980",M,A+,PA,99298.0,Tricare,717.024.4697,"March 04, 2020",N
2441,PT-00555,Jennifer,Rodriguez,12-19-1986,F,O+,NJ,34298.0,Cigna,(050) 631-5571,21-Jun-2012,N
2457,pt-01623,Christina,Moore,"April 19, 1961",F,B+,OH,11776.0,Kaiser Permanente,+16319504095,28-May-2015,Y
2477,PT-02141,Kimberly,Gonzalez,"April 02, 1974",F,NaN,CA,94738.0,Aetna,284-826-2176,2019-12-13,N
2508,PT-02145,Mark,Cruz,"November 04, 1970",M,A+,MA,93000.0,Tricare,059-204-5616,"December 11, 2016",N
2557,PT-02482,Matthew,Martinez,"July 31, 1997",M,NaN,NY,30415.0,Cigna,252.566.8004,2018-02-20,N
2559,PT-02920,Charles,Lewis,1961-02-14,M,O-,CA,92809.0,Aetna,+14042520885,"July 29, 2012",N
2560,PT-00410,Heather,Evans,"July 22, 2012",F,A+,IL,44638.0,Tricare,+17674014374,08-24-2013,N
2619,PT-03998,Edward,Martin,16-May-2014,M,O+,CA,44214.0,Aetna,5970244155,2013-03-11,N
2727,PT-03647,Cynthia,Williams,05-25-1959,F,A+,PA,73535.0,Medicare,162.756.9478,2011-02-01,Y
2737,PT-00557,Timothy,Stewart,03/03/1981,M,A+,IL,32293.0,Blue Cross Blue Shield,402.053.1613,"March 08, 2020",N
2797,PT-02500,Christine,Smith,1946-10-26,F,O+,CA,15091.0,Blue Cross Blue Shield,449.465.3382,"October 27, 2014",N
2931,PT-01502,Brian,Nguyen,11-Apr-1971,M,O+,IL,61011.0,UnitedHealthcare,NaN,03-22-2012,N
2976,PT-01179,Julie,Brown,25-Nov-1956,F,O+,OH,36413.0,Aetna,962.717.8467,12/02/2021,Y
3021,PT-03572,Ashley,Torres,2015-05-12,F,O+,FL,66951.0,Kaiser Permanente,958-770-5719,08/05/2011,Y
3051,PT-01827,Janet,Lee,08/16/1988,F,A+,TX,41286.0,Tricare,+17327473400,04-Mar-2024,N
3077,PT-03413,Nathan,Robinson,04/18/1992,M,AB+,NJ,66270.0,Medicaid,NaN,30-Jun-2011,N
3080,PT-00742,Ashley,Martin,1982-02-23,F,A-,CT,71355.0,Self-Pay,+12639286272,01-Feb-2019,N
3102,PT-00685,Ryan,Moore,04-03-1980,M,A-,PA,72501.0,UnitedHealthcare,(677) 391-6170,30-Mar-2024,N
3135,PT-04103,Rachel,Ramirez,"June 19, 2001",F,O+,CA,25432.0,Medicare,+18475876344,"November 20, 2020",N
3153,pt-01036,Patrick,Turner,05-02-1974,M,B+,CA,83763.0,Medicaid,6142734477,2011-12-08,N
3172,PT-04059,Margaret,Smith,1984-02-20,F,A-,IL,NaN,Medicare,+18353548710,11/05/2013,N
3191,PT-00911,Emily,Hernandez,12/21/2005,F,A+,FL,57668.0,Tricare,013.991.9657,02-10-2014,N
3276,PT-02965,Margaret,Brown,"September 05, 2010",F,A+,CT,19099.0,Cigna,694.463.2626,2021-01-20,N
3282,PT-02891,Olivia,Thomas,10/22/1977,F,O+,OH,32430.0,Medicaid,3337197051,2016-06-11,N
3293,PT-03417,Margaret,Sanchez,05-16-1940,F,B+,CA,36807.0,UnitedHealthcare,7000949930,02-01-2013,Y
3325,PT-01662,Christine,Wilson,08/24/1988,F,A+,FL,88081.0,Humana,+19242232771,05/31/2023,N
3359,PT-01790,Robert,Thompson,28-Feb-1964,M,B+,CA,85586.0,Medicaid,452-294-9014,11-Dec-2022,N
3362,PT03454,Eric,Carter,06/12/1990,M,A-,CA,45449.0,UnitedHealthcare,574-407-2869,06/10/2011,N
3368,PT-03682,Joseph,Mitchell,06-01-1930,M,O+,IL,93119.0,Self-Pay,926-016-3597,03-29-2021,N
3445,PT-02471,Emma,Lopez,15-Feb-2019,F,O+,MA,20466.0,Aetna,+10140536011,11/21/2018,Y
3500,pt-03215,Thomas,Martinez,11-21-1976,M,A-,CA,70975.0,Self-Pay,(090) 251-6504,04/18/2016,N
3607,PT-00362,Jeffrey,Stewart,11/04/1973,M,O+,PA,43479.0,Medicaid,+15062906164,"August 15, 2023",N

In [60]:
patients=patients.drop_duplicates()
patients.head(50)

,patient_id,first_name,last_name,date_of_birth,gender,blood_type,state,zip_code,insurance_provider,phone,registration_date,chronic_condition_flag
0,PT00984,Sharon,Hall,09-Dec-2013,F,A+,TX,25865.0,UnitedHealthcare,670-712-7399,"March 11, 2022",N
1,PT-01865,Victoria,Williams,11-26-1938,F,O+,IL,89911.0,Tricare,+11438335180,07-17-2020,N
2,PT-00032,Amy,Johnson,1947-06-19,F,A+,NJ,56848.0,Medicaid,4797990275,2015-09-26,Y
3,PT-02473,Sarah,Garcia,13-Oct-1976,F,O+,CA,55898.0,Self-Pay,+16974954932,"May 20, 2013",N
4,PT-03804,Amy,Johnson,29-May-2008,F,O+,TX,60856.0,Humana,678-881-2019,02/20/2018,N
5,PT-03251,Donna,Campbell,1975-03-16,F,AB+,FL,24158.0,Cigna,893.838.0922,12/14/2016,N
6,PT-01064,Brandon,Flores,"March 10, 1982",M,O+,IL,80514.0,Cigna,(978) 548-3893,"November 06, 2021",N
7,PT-02447,Linda,Sanchez,"February 04, 2007",F,O-,IL,65850.0,Humana,788-549-6822,2018-04-27,N
8,PT-00965,Nathan,Wilson,"August 20, 2016",M,NaN,NJ,20299.0,UnitedHealthcare,997-997-5281,10-22-2022,N
9,PT-02952,Helen,Garcia,2000-08-09,F,AB+,NY,48926.0,Aetna,881-566-8040,2012-09-16,N
10,PT-02658,Joseph,Scott,08-May-1943,M,A+,CA,54955.0,UnitedHealthcare,864-646-0041,15-Apr-2022,N
11,PT-00704,Jerry,Wright,08/31/1943,M,B+,PA,63089.0,Cigna,570.420.0455,2012-10-02,N
12,PT-00186,Rachel,Taylor,01-12-1950,F,O+,CA,98478.0,Aetna,9627927756,04-19-2010,Y
13,PT-01849,Brenda,Harris,12/22/1932,F,B-,NY,93461.0,Aetna,+14264223116,12-Aug-2022,N
14,PT-02547,Betty,Walker,12-May-1966,F,O+,CT,40995.0,Cigna,447-186-3693,09-Mar-2012,N
15,PT-00389,Kimberly,Flores,"January 23, 1944",F,NaN,IL,94547.0,Self-Pay,4418780280,02/25/2012,Y
16,PT-02118,Edward,Smith,18-Dec-1979,M,O+,OH,34859.0,Cigna,(834) 697-4330,02/03/2019,N
17,PT-03845,Katherine,Ramirez,1950-08-11,F,O+,MA,20008.0,Aetna,0758240931,01/30/2017,Y
18,PT-00129,Sarah,Gonzalez,03-26-1943,F,AB-,TX,44925.0,Humana,(196) 839-6197,"October 26, 2016",N
19,PT-03285,Michelle,Moore,1997-12-30,F,O+,PA,96281.0,Tricare,062.884.2126,2015-02-28,N
20,PT-04044,Christine,Walker,02-12-2007,F,B+,CA,28365.0,Medicare,(501) 725-7449,21-Jul-2024,N
21,PT-01589,Janet,Lee,01/31/1961,F,O+,FL,13234.0,Medicare,421.666.7466,09/11/2015,N
22,PT-01556,Elizabeth,Scott,21-Jan-1942,F,O+,CT,89567.0,Kaiser Permanente,+18445952760,09/13/2020,N
23,PT-01439,Peter,WALKER,1955-04-13,M,B+,FL,96056.0,Kaiser Permanente,+15345266346,10/31/2011,N
24,PT-03614,Walter,Smith,09-Dec-1985,M,A+,FL,17411.0,Humana,574.879.9949,2019-01-03,N
25,PT-03127,Donald,Martin,2001-04-21,M,O+,NY,68949.0,Self-Pay,+19555805815,07-22-2010,N
26,PT-00999,Olivia,Ramirez,06-Sep-2003,F,A+,MA,49408.0,Self-Pay,823-171-3782,"January 12, 2010",N
27,PT-02270,James,Rodriguez,08-24-1980,M,O+,OH,38906.0,Medicare,+18645775770,2012-08-20,N
28,PT-00818,Samantha,Moore,14-Aug-2022,F,O-,FL,20900.0,Kaiser Permanente,NaN,"June 16, 2012",N
29,PT-00694,Jerry,Moore,12-21-1990,M,O+,CA,94486.0,Medicare,1959903845,13-Sep-2011,N
30,PT-01336,Susan,Harris,06-17-1966,F,A+,IL,87741.0,Tricare,NaN,2013-04-22,N
31,PT-02818,Margaret,Diaz,1974-04-17,F,B+,OH,17817.0,Medicare,639.234.3391,12/02/2021,N
32,PT-03237,Jennifer,Smith,13-May-1937,F,B+,NY,61160.0,Medicaid,784.561.0722,2011-06-30,N
33,PT-01161,Rebecca,Martinez,1969-08-12,F,O+,CT,45854.0,Tricare,8784511163,2022-11-29,N
34,PT-02477,Carlos,Ramirez,06-19-2014,M,NaN,MA,51441.0,Medicare,531-561-1401,"September 05, 2014",N
35,PT-02662,Joyce,Campbell,02-08-2009,F,B-,IL,80907.0,Aetna,+13253632264,15-Sep-2022,N
36,PT-01213,Dennis,Williams,07/14/2000,M,A+,IL,36900.0,Tricare,4391980720,26-Jun-2023,Y
37,PT-03407,Melissa,Garcia,23-Dec-1980,F,B+,TX,74348.0,Self-Pay,+18272328773,18-Dec-2020,N
38,PT-01754,Dennis,Brown,"March 10, 1970",M,O+,OH,47934.0,Humana,+14634823120,2016-01-29,Y
39,PT-00906,Edward,Baker,12/01/1953,M,O-,FL,65796.0,Humana,(041) 324-7451,2024-09-09,Y
40,PT-00401,Brenda,Brown,01-14-1945,F,O+,IL,78063.0,Self-Pay,5274955943,06-27-2022,N
41,pt-04008,Margaret,Lewis,"September 02, 1960",F,O-,NJ,55543.0,Blue Cross Blue Shield,614.013.9900,"January 15, 2017",N
42,PT-00227,Kimberly,Williams,1942-12-13,F,O+,NY,68388.0,Self-Pay,969.914.1099,02-19-2017,N
43,PT-03511,Patricia,King,04/04/1968,F,A+,OH,71538.0,Aetna,1349687952,09-30-2015,N
44,PT-01935,Brandon,Edwards,12/21/1945,M,O-,CA,81341.0,Self-Pay,8235286524,2023-03-10,N
45,PT-01747,Jonathan,Torres,10-04-1936,M,AB+,CT,14688.0,Medicaid,5977021934,2011-05-13,N
46,PT-00779,Ryan,Hernandez,10/05/1932,M,O+,CA,92549.0,Aetna,(429) 812-5443,19-Feb-2018,N
47,PT-00950,George,Nelson,08/26/1981,M,A+,CT,30553.0,Blue Cross Blue Shield,0936956068,"March 22, 2024",N
48,PT-03316,David,Flores,31-May-1991,M,O+,CA,63747.0,UnitedHealthcare,(417) 971-5101,28-Oct-2011,Y
49,PT-00721,Jennifer,Jackson,"March 26, 1966",F,A+,TX,29475.0,Aetna,(950) 801-2174,"August 05, 2014",Y

In [61]:
patients['first_name']=patients['first_name'].str.title()
patients['last_name']=patients['last_name'].str.title()

patients[['first_name','last_name']].head(50)

   first_name  last_name
0      Sharon       Hall
1    Victoria   Williams
2         Amy    Johnson
3       Sarah     Garcia
4         Amy    Johnson
5       Donna   Campbell
6     Brandon     Flores
7       Linda    Sanchez
8      Nathan     Wilson
9       Helen     Garcia
10     Joseph      Scott
11      Jerry     Wright
12     Rachel     Taylor
13     Brenda     Harris
14      Betty     Walker
15   Kimberly     Flores
16     Edward      Smith
17  Katherine    Ramirez
18      Sarah   Gonzalez
19   Michelle      Moore
20  Christine     Walker
21      Janet        Lee
22  Elizabeth      Scott
23      Peter     Walker
24     Walter      Smith
25     Donald     Martin
26     Olivia    Ramirez
27      James  Rodriguez
28   Samantha      Moore
29      Jerry      Moore
30      Susan     Harris
31   Margaret       Diaz
32   Jennifer      Smith
33    Rebecca   Martinez
34     Carlos    Ramirez
35      Joyce   Campbell
36     Dennis   Williams
37    Melissa     Garcia
38     Dennis      Brown
39     Edward      Baker
40     Brenda      Brown
41   Margaret      Lewis
42   Kimberly   Williams
43   Patricia       King
44    Brandon    Edwards
45   Jonathan     Torres
46       Ryan  Hernandez
47     George     Nelson
48      David     Flores
49   Jennifer    Jackson

In [62]:
patients['blood_type'].value_counts()

O+     1349
A+     1193
B+      293
O-      261
A-      180
AB+     120
B-       75
AB-      36
Name: blood_type, dtype: int64

In [63]:
patients['blood_type']=patients['blood_type'].fillna('Unknown')
patients.head(50)

,patient_id,first_name,last_name,date_of_birth,gender,blood_type,state,zip_code,insurance_provider,phone,registration_date,chronic_condition_flag
0,PT00984,Sharon,Hall,09-Dec-2013,F,A+,TX,25865.0,UnitedHealthcare,670-712-7399,"March 11, 2022",N
1,PT-01865,Victoria,Williams,11-26-1938,F,O+,IL,89911.0,Tricare,+11438335180,07-17-2020,N
2,PT-00032,Amy,Johnson,1947-06-19,F,A+,NJ,56848.0,Medicaid,4797990275,2015-09-26,Y
3,PT-02473,Sarah,Garcia,13-Oct-1976,F,O+,CA,55898.0,Self-Pay,+16974954932,"May 20, 2013",N
4,PT-03804,Amy,Johnson,29-May-2008,F,O+,TX,60856.0,Humana,678-881-2019,02/20/2018,N
5,PT-03251,Donna,Campbell,1975-03-16,F,AB+,FL,24158.0,Cigna,893.838.0922,12/14/2016,N
6,PT-01064,Brandon,Flores,"March 10, 1982",M,O+,IL,80514.0,Cigna,(978) 548-3893,"November 06, 2021",N
7,PT-02447,Linda,Sanchez,"February 04, 2007",F,O-,IL,65850.0,Humana,788-549-6822,2018-04-27,N
8,PT-00965,Nathan,Wilson,"August 20, 2016",M,Unknown,NJ,20299.0,UnitedHealthcare,997-997-5281,10-22-2022,N
9,PT-02952,Helen,Garcia,2000-08-09,F,AB+,NY,48926.0,Aetna,881-566-8040,2012-09-16,N
10,PT-02658,Joseph,Scott,08-May-1943,M,A+,CA,54955.0,UnitedHealthcare,864-646-0041,15-Apr-2022,N
11,PT-00704,Jerry,Wright,08/31/1943,M,B+,PA,63089.0,Cigna,570.420.0455,2012-10-02,N
12,PT-00186,Rachel,Taylor,01-12-1950,F,O+,CA,98478.0,Aetna,9627927756,04-19-2010,Y
13,PT-01849,Brenda,Harris,12/22/1932,F,B-,NY,93461.0,Aetna,+14264223116,12-Aug-2022,N
14,PT-02547,Betty,Walker,12-May-1966,F,O+,CT,40995.0,Cigna,447-186-3693,09-Mar-2012,N
15,PT-00389,Kimberly,Flores,"January 23, 1944",F,Unknown,IL,94547.0,Self-Pay,4418780280,02/25/2012,Y
16,PT-02118,Edward,Smith,18-Dec-1979,M,O+,OH,34859.0,Cigna,(834) 697-4330,02/03/2019,N
17,PT-03845,Katherine,Ramirez,1950-08-11,F,O+,MA,20008.0,Aetna,0758240931,01/30/2017,Y
18,PT-00129,Sarah,Gonzalez,03-26-1943,F,AB-,TX,44925.0,Humana,(196) 839-6197,"October 26, 2016",N
19,PT-03285,Michelle,Moore,1997-12-30,F,O+,PA,96281.0,Tricare,062.884.2126,2015-02-28,N
20,PT-04044,Christine,Walker,02-12-2007,F,B+,CA,28365.0,Medicare,(501) 725-7449,21-Jul-2024,N
21,PT-01589,Janet,Lee,01/31/1961,F,O+,FL,13234.0,Medicare,421.666.7466,09/11/2015,N
22,PT-01556,Elizabeth,Scott,21-Jan-1942,F,O+,CT,89567.0,Kaiser Permanente,+18445952760,09/13/2020,N
23,PT-01439,Peter,Walker,1955-04-13,M,B+,FL,96056.0,Kaiser Permanente,+15345266346,10/31/2011,N
24,PT-03614,Walter,Smith,09-Dec-1985,M,A+,FL,17411.0,Humana,574.879.9949,2019-01-03,N
25,PT-03127,Donald,Martin,2001-04-21,M,O+,NY,68949.0,Self-Pay,+19555805815,07-22-2010,N
26,PT-00999,Olivia,Ramirez,06-Sep-2003,F,A+,MA,49408.0,Self-Pay,823-171-3782,"January 12, 2010",N
27,PT-02270,James,Rodriguez,08-24-1980,M,O+,OH,38906.0,Medicare,+18645775770,2012-08-20,N
28,PT-00818,Samantha,Moore,14-Aug-2022,F,O-,FL,20900.0,Kaiser Permanente,NaN,"June 16, 2012",N
29,PT-00694,Jerry,Moore,12-21-1990,M,O+,CA,94486.0,Medicare,1959903845,13-Sep-2011,N
30,PT-01336,Susan,Harris,06-17-1966,F,A+,IL,87741.0,Tricare,NaN,2013-04-22,N
31,PT-02818,Margaret,Diaz,1974-04-17,F,B+,OH,17817.0,Medicare,639.234.3391,12/02/2021,N
32,PT-03237,Jennifer,Smith,13-May-1937,F,B+,NY,61160.0,Medicaid,784.561.0722,2011-06-30,N
33,PT-01161,Rebecca,Martinez,1969-08-12,F,O+,CT,45854.0,Tricare,8784511163,2022-11-29,N
34,PT-02477,Carlos,Ramirez,06-19-2014,M,Unknown,MA,51441.0,Medicare,531-561-1401,"September 05, 2014",N
35,PT-02662,Joyce,Campbell,02-08-2009,F,B-,IL,80907.0,Aetna,+13253632264,15-Sep-2022,N
36,PT-01213,Dennis,Williams,07/14/2000,M,A+,IL,36900.0,Tricare,4391980720,26-Jun-2023,Y
37,PT-03407,Melissa,Garcia,23-Dec-1980,F,B+,TX,74348.0,Self-Pay,+18272328773,18-Dec-2020,N
38,PT-01754,Dennis,Brown,"March 10, 1970",M,O+,OH,47934.0,Humana,+14634823120,2016-01-29,Y
39,PT-00906,Edward,Baker,12/01/1953,M,O-,FL,65796.0,Humana,(041) 324-7451,2024-09-09,Y
40,PT-00401,Brenda,Brown,01-14-1945,F,O+,IL,78063.0,Self-Pay,5274955943,06-27-2022,N
41,pt-04008,Margaret,Lewis,"September 02, 1960",F,O-,NJ,55543.0,Blue Cross Blue Shield,614.013.9900,"January 15, 2017",N
42,PT-00227,Kimberly,Williams,1942-12-13,F,O+,NY,68388.0,Self-Pay,969.914.1099,02-19-2017,N
43,PT-03511,Patricia,King,04/04/1968,F,A+,OH,71538.0,Aetna,1349687952,09-30-2015,N
44,PT-01935,Brandon,Edwards,12/21/1945,M,O-,CA,81341.0,Self-Pay,8235286524,2023-03-10,N
45,PT-01747,Jonathan,Torres,10-04-1936,M,AB+,CT,14688.0,Medicaid,5977021934,2011-05-13,N
46,PT-00779,Ryan,Hernandez,10/05/1932,M,O+,CA,92549.0,Aetna,(429) 812-5443,19-Feb-2018,N
47,PT-00950,George,Nelson,08/26/1981,M,A+,CT,30553.0,Blue Cross Blue Shield,0936956068,"March 22, 2024",N
48,PT-03316,David,Flores,31-May-1991,M,O+,CA,63747.0,UnitedHealthcare,(417) 971-5101,28-Oct-2011,Y
49,PT-00721,Jennifer,Jackson,"March 26, 1966",F,A+,TX,29475.0,Aetna,(950) 801-2174,"August 05, 2014",Y

In [64]:
patients['state'].value_counts()

TX    393
NJ    387
OH    379
CA    373
IL    370
FL    357
CT    354
PA    347
MA    342
NY    342
Name: state, dtype: int64

In [65]:
patients['chronic_condition_flag'].value_counts()

N    2810
Y     834
Name: chronic_condition_flag, dtype: int64

In [66]:
patients['patient_id']=patients['patient_id'].str.strip('PT-')
patients['patient_id']=patients['patient_id'].str.strip('pt-')
patients.head(50)

,patient_id,first_name,last_name,date_of_birth,gender,blood_type,state,zip_code,insurance_provider,phone,registration_date,chronic_condition_flag
0,00984,Sharon,Hall,09-Dec-2013,F,A+,TX,25865.0,UnitedHealthcare,670-712-7399,"March 11, 2022",N
1,01865,Victoria,Williams,11-26-1938,F,O+,IL,89911.0,Tricare,+11438335180,07-17-2020,N
2,00032,Amy,Johnson,1947-06-19,F,A+,NJ,56848.0,Medicaid,4797990275,2015-09-26,Y
3,02473,Sarah,Garcia,13-Oct-1976,F,O+,CA,55898.0,Self-Pay,+16974954932,"May 20, 2013",N
4,03804,Amy,Johnson,29-May-2008,F,O+,TX,60856.0,Humana,678-881-2019,02/20/2018,N
5,03251,Donna,Campbell,1975-03-16,F,AB+,FL,24158.0,Cigna,893.838.0922,12/14/2016,N
6,01064,Brandon,Flores,"March 10, 1982",M,O+,IL,80514.0,Cigna,(978) 548-3893,"November 06, 2021",N
7,02447,Linda,Sanchez,"February 04, 2007",F,O-,IL,65850.0,Humana,788-549-6822,2018-04-27,N
8,00965,Nathan,Wilson,"August 20, 2016",M,Unknown,NJ,20299.0,UnitedHealthcare,997-997-5281,10-22-2022,N
9,02952,Helen,Garcia,2000-08-09,F,AB+,NY,48926.0,Aetna,881-566-8040,2012-09-16,N
10,02658,Joseph,Scott,08-May-1943,M,A+,CA,54955.0,UnitedHealthcare,864-646-0041,15-Apr-2022,N
11,00704,Jerry,Wright,08/31/1943,M,B+,PA,63089.0,Cigna,570.420.0455,2012-10-02,N
12,00186,Rachel,Taylor,01-12-1950,F,O+,CA,98478.0,Aetna,9627927756,04-19-2010,Y
13,01849,Brenda,Harris,12/22/1932,F,B-,NY,93461.0,Aetna,+14264223116,12-Aug-2022,N
14,02547,Betty,Walker,12-May-1966,F,O+,CT,40995.0,Cigna,447-186-3693,09-Mar-2012,N
15,00389,Kimberly,Flores,"January 23, 1944",F,Unknown,IL,94547.0,Self-Pay,4418780280,02/25/2012,Y
16,02118,Edward,Smith,18-Dec-1979,M,O+,OH,34859.0,Cigna,(834) 697-4330,02/03/2019,N
17,03845,Katherine,Ramirez,1950-08-11,F,O+,MA,20008.0,Aetna,0758240931,01/30/2017,Y
18,00129,Sarah,Gonzalez,03-26-1943,F,AB-,TX,44925.0,Humana,(196) 839-6197,"October 26, 2016",N
19,03285,Michelle,Moore,1997-12-30,F,O+,PA,96281.0,Tricare,062.884.2126,2015-02-28,N
20,04044,Christine,Walker,02-12-2007,F,B+,CA,28365.0,Medicare,(501) 725-7449,21-Jul-2024,N
21,01589,Janet,Lee,01/31/1961,F,O+,FL,13234.0,Medicare,421.666.7466,09/11/2015,N
22,01556,Elizabeth,Scott,21-Jan-1942,F,O+,CT,89567.0,Kaiser Permanente,+18445952760,09/13/2020,N
23,01439,Peter,Walker,1955-04-13,M,B+,FL,96056.0,Kaiser Permanente,+15345266346,10/31/2011,N
24,03614,Walter,Smith,09-Dec-1985,M,A+,FL,17411.0,Humana,574.879.9949,2019-01-03,N
25,03127,Donald,Martin,2001-04-21,M,O+,NY,68949.0,Self-Pay,+19555805815,07-22-2010,N
26,00999,Olivia,Ramirez,06-Sep-2003,F,A+,MA,49408.0,Self-Pay,823-171-3782,"January 12, 2010",N
27,02270,James,Rodriguez,08-24-1980,M,O+,OH,38906.0,Medicare,+18645775770,2012-08-20,N
28,00818,Samantha,Moore,14-Aug-2022,F,O-,FL,20900.0,Kaiser Permanente,NaN,"June 16, 2012",N
29,00694,Jerry,Moore,12-21-1990,M,O+,CA,94486.0,Medicare,1959903845,13-Sep-2011,N
30,01336,Susan,Harris,06-17-1966,F,A+,IL,87741.0,Tricare,NaN,2013-04-22,N
31,02818,Margaret,Diaz,1974-04-17,F,B+,OH,17817.0,Medicare,639.234.3391,12/02/2021,N
32,03237,Jennifer,Smith,13-May-1937,F,B+,NY,61160.0,Medicaid,784.561.0722,2011-06-30,N
33,01161,Rebecca,Martinez,1969-08-12,F,O+,CT,45854.0,Tricare,8784511163,2022-11-29,N
34,02477,Carlos,Ramirez,06-19-2014,M,Unknown,MA,51441.0,Medicare,531-561-1401,"September 05, 2014",N
35,02662,Joyce,Campbell,02-08-2009,F,B-,IL,80907.0,Aetna,+13253632264,15-Sep-2022,N
36,01213,Dennis,Williams,07/14/2000,M,A+,IL,36900.0,Tricare,4391980720,26-Jun-2023,Y
37,03407,Melissa,Garcia,23-Dec-1980,F,B+,TX,74348.0,Self-Pay,+18272328773,18-Dec-2020,N
38,01754,Dennis,Brown,"March 10, 1970",M,O+,OH,47934.0,Humana,+14634823120,2016-01-29,Y
39,00906,Edward,Baker,12/01/1953,M,O-,FL,65796.0,Humana,(041) 324-7451,2024-09-09,Y
40,00401,Brenda,Brown,01-14-1945,F,O+,IL,78063.0,Self-Pay,5274955943,06-27-2022,N
41,04008,Margaret,Lewis,"September 02, 1960",F,O-,NJ,55543.0,Blue Cross Blue Shield,614.013.9900,"January 15, 2017",N
42,00227,Kimberly,Williams,1942-12-13,F,O+,NY,68388.0,Self-Pay,969.914.1099,02-19-2017,N
43,03511,Patricia,King,04/04/1968,F,A+,OH,71538.0,Aetna,1349687952,09-30-2015,N
44,01935,Brandon,Edwards,12/21/1945,M,O-,CA,81341.0,Self-Pay,8235286524,2023-03-10,N
45,01747,Jonathan,Torres,10-04-1936,M,AB+,CT,14688.0,Medicaid,5977021934,2011-05-13,N
46,00779,Ryan,Hernandez,10/05/1932,M,O+,CA,92549.0,Aetna,(429) 812-5443,19-Feb-2018,N
47,00950,George,Nelson,08/26/1981,M,A+,CT,30553.0,Blue Cross Blue Shield,0936956068,"March 22, 2024",N
48,03316,David,Flores,31-May-1991,M,O+,CA,63747.0,UnitedHealthcare,(417) 971-5101,28-Oct-2011,Y
49,00721,Jennifer,Jackson,"March 26, 1966",F,A+,TX,29475.0,Aetna,(950) 801-2174,"August 05, 2014",Y

In [67]:
patients['date_of_birth']=pd.to_datetime(patients['date_of_birth']).dt.date
patients.head(50)

,patient_id,first_name,last_name,date_of_birth,gender,blood_type,state,zip_code,insurance_provider,phone,registration_date,chronic_condition_flag
0,00984,Sharon,Hall,2013-12-09,F,A+,TX,25865.0,UnitedHealthcare,670-712-7399,"March 11, 2022",N
1,01865,Victoria,Williams,1938-11-26,F,O+,IL,89911.0,Tricare,+11438335180,07-17-2020,N
2,00032,Amy,Johnson,1947-06-19,F,A+,NJ,56848.0,Medicaid,4797990275,2015-09-26,Y
3,02473,Sarah,Garcia,1976-10-13,F,O+,CA,55898.0,Self-Pay,+16974954932,"May 20, 2013",N
4,03804,Amy,Johnson,2008-05-29,F,O+,TX,60856.0,Humana,678-881-2019,02/20/2018,N
5,03251,Donna,Campbell,1975-03-16,F,AB+,FL,24158.0,Cigna,893.838.0922,12/14/2016,N
6,01064,Brandon,Flores,1982-03-10,M,O+,IL,80514.0,Cigna,(978) 548-3893,"November 06, 2021",N
7,02447,Linda,Sanchez,2007-02-04,F,O-,IL,65850.0,Humana,788-549-6822,2018-04-27,N
8,00965,Nathan,Wilson,2016-08-20,M,Unknown,NJ,20299.0,UnitedHealthcare,997-997-5281,10-22-2022,N
9,02952,Helen,Garcia,2000-08-09,F,AB+,NY,48926.0,Aetna,881-566-8040,2012-09-16,N
10,02658,Joseph,Scott,1943-05-08,M,A+,CA,54955.0,UnitedHealthcare,864-646-0041,15-Apr-2022,N
11,00704,Jerry,Wright,1943-08-31,M,B+,PA,63089.0,Cigna,570.420.0455,2012-10-02,N
12,00186,Rachel,Taylor,1950-01-12,F,O+,CA,98478.0,Aetna,9627927756,04-19-2010,Y
13,01849,Brenda,Harris,1932-12-22,F,B-,NY,93461.0,Aetna,+14264223116,12-Aug-2022,N
14,02547,Betty,Walker,1966-05-12,F,O+,CT,40995.0,Cigna,447-186-3693,09-Mar-2012,N
15,00389,Kimberly,Flores,1944-01-23,F,Unknown,IL,94547.0,Self-Pay,4418780280,02/25/2012,Y
16,02118,Edward,Smith,1979-12-18,M,O+,OH,34859.0,Cigna,(834) 697-4330,02/03/2019,N
17,03845,Katherine,Ramirez,1950-08-11,F,O+,MA,20008.0,Aetna,0758240931,01/30/2017,Y
18,00129,Sarah,Gonzalez,1943-03-26,F,AB-,TX,44925.0,Humana,(196) 839-6197,"October 26, 2016",N
19,03285,Michelle,Moore,1997-12-30,F,O+,PA,96281.0,Tricare,062.884.2126,2015-02-28,N
20,04044,Christine,Walker,2007-02-12,F,B+,CA,28365.0,Medicare,(501) 725-7449,21-Jul-2024,N
21,01589,Janet,Lee,1961-01-31,F,O+,FL,13234.0,Medicare,421.666.7466,09/11/2015,N
22,01556,Elizabeth,Scott,1942-01-21,F,O+,CT,89567.0,Kaiser Permanente,+18445952760,09/13/2020,N
23,01439,Peter,Walker,1955-04-13,M,B+,FL,96056.0,Kaiser Permanente,+15345266346,10/31/2011,N
24,03614,Walter,Smith,1985-12-09,M,A+,FL,17411.0,Humana,574.879.9949,2019-01-03,N
25,03127,Donald,Martin,2001-04-21,M,O+,NY,68949.0,Self-Pay,+19555805815,07-22-2010,N
26,00999,Olivia,Ramirez,2003-09-06,F,A+,MA,49408.0,Self-Pay,823-171-3782,"January 12, 2010",N
27,02270,James,Rodriguez,1980-08-24,M,O+,OH,38906.0,Medicare,+18645775770,2012-08-20,N
28,00818,Samantha,Moore,2022-08-14,F,O-,FL,20900.0,Kaiser Permanente,NaN,"June 16, 2012",N
29,00694,Jerry,Moore,1990-12-21,M,O+,CA,94486.0,Medicare,1959903845,13-Sep-2011,N
30,01336,Susan,Harris,1966-06-17,F,A+,IL,87741.0,Tricare,NaN,2013-04-22,N
31,02818,Margaret,Diaz,1974-04-17,F,B+,OH,17817.0,Medicare,639.234.3391,12/02/2021,N
32,03237,Jennifer,Smith,1937-05-13,F,B+,NY,61160.0,Medicaid,784.561.0722,2011-06-30,N
33,01161,Rebecca,Martinez,1969-08-12,F,O+,CT,45854.0,Tricare,8784511163,2022-11-29,N
34,02477,Carlos,Ramirez,2014-06-19,M,Unknown,MA,51441.0,Medicare,531-561-1401,"September 05, 2014",N
35,02662,Joyce,Campbell,2009-02-08,F,B-,IL,80907.0,Aetna,+13253632264,15-Sep-2022,N
36,01213,Dennis,Williams,2000-07-14,M,A+,IL,36900.0,Tricare,4391980720,26-Jun-2023,Y
37,03407,Melissa,Garcia,1980-12-23,F,B+,TX,74348.0,Self-Pay,+18272328773,18-Dec-2020,N
38,01754,Dennis,Brown,1970-03-10,M,O+,OH,47934.0,Humana,+14634823120,2016-01-29,Y
39,00906,Edward,Baker,1953-12-01,M,O-,FL,65796.0,Humana,(041) 324-7451,2024-09-09,Y
40,00401,Brenda,Brown,1945-01-14,F,O+,IL,78063.0,Self-Pay,5274955943,06-27-2022,N
41,04008,Margaret,Lewis,1960-09-02,F,O-,NJ,55543.0,Blue Cross Blue Shield,614.013.9900,"January 15, 2017",N
42,00227,Kimberly,Williams,1942-12-13,F,O+,NY,68388.0,Self-Pay,969.914.1099,02-19-2017,N
43,03511,Patricia,King,1968-04-04,F,A+,OH,71538.0,Aetna,1349687952,09-30-2015,N
44,01935,Brandon,Edwards,1945-12-21,M,O-,CA,81341.0,Self-Pay,8235286524,2023-03-10,N
45,01747,Jonathan,Torres,1936-10-04,M,AB+,CT,14688.0,Medicaid,5977021934,2011-05-13,N
46,00779,Ryan,Hernandez,1932-10-05,M,O+,CA,92549.0,Aetna,(429) 812-5443,19-Feb-2018,N
47,00950,George,Nelson,1981-08-26,M,A+,CT,30553.0,Blue Cross Blue Shield,0936956068,"March 22, 2024",N
48,03316,David,Flores,1991-05-31,M,O+,CA,63747.0,UnitedHealthcare,(417) 971-5101,28-Oct-2011,Y
49,00721,Jennifer,Jackson,1966-03-26,F,A+,TX,29475.0,Aetna,(950) 801-2174,"August 05, 2014",Y

In [68]:
patients['registration_date']=pd.to_datetime(patients['registration_date']).dt.date
patients.head(50)

,patient_id,first_name,last_name,date_of_birth,gender,blood_type,state,zip_code,insurance_provider,phone,registration_date,chronic_condition_flag
0,00984,Sharon,Hall,2013-12-09,F,A+,TX,25865.0,UnitedHealthcare,670-712-7399,2022-03-11,N
1,01865,Victoria,Williams,1938-11-26,F,O+,IL,89911.0,Tricare,+11438335180,2020-07-17,N
2,00032,Amy,Johnson,1947-06-19,F,A+,NJ,56848.0,Medicaid,4797990275,2015-09-26,Y
3,02473,Sarah,Garcia,1976-10-13,F,O+,CA,55898.0,Self-Pay,+16974954932,2013-05-20,N
4,03804,Amy,Johnson,2008-05-29,F,O+,TX,60856.0,Humana,678-881-2019,2018-02-20,N
5,03251,Donna,Campbell,1975-03-16,F,AB+,FL,24158.0,Cigna,893.838.0922,2016-12-14,N
6,01064,Brandon,Flores,1982-03-10,M,O+,IL,80514.0,Cigna,(978) 548-3893,2021-11-06,N
7,02447,Linda,Sanchez,2007-02-04,F,O-,IL,65850.0,Humana,788-549-6822,2018-04-27,N
8,00965,Nathan,Wilson,2016-08-20,M,Unknown,NJ,20299.0,UnitedHealthcare,997-997-5281,2022-10-22,N
9,02952,Helen,Garcia,2000-08-09,F,AB+,NY,48926.0,Aetna,881-566-8040,2012-09-16,N
10,02658,Joseph,Scott,1943-05-08,M,A+,CA,54955.0,UnitedHealthcare,864-646-0041,2022-04-15,N
11,00704,Jerry,Wright,1943-08-31,M,B+,PA,63089.0,Cigna,570.420.0455,2012-10-02,N
12,00186,Rachel,Taylor,1950-01-12,F,O+,CA,98478.0,Aetna,9627927756,2010-04-19,Y
13,01849,Brenda,Harris,1932-12-22,F,B-,NY,93461.0,Aetna,+14264223116,2022-08-12,N
14,02547,Betty,Walker,1966-05-12,F,O+,CT,40995.0,Cigna,447-186-3693,2012-03-09,N
15,00389,Kimberly,Flores,1944-01-23,F,Unknown,IL,94547.0,Self-Pay,4418780280,2012-02-25,Y
16,02118,Edward,Smith,1979-12-18,M,O+,OH,34859.0,Cigna,(834) 697-4330,2019-02-03,N
17,03845,Katherine,Ramirez,1950-08-11,F,O+,MA,20008.0,Aetna,0758240931,2017-01-30,Y
18,00129,Sarah,Gonzalez,1943-03-26,F,AB-,TX,44925.0,Humana,(196) 839-6197,2016-10-26,N
19,03285,Michelle,Moore,1997-12-30,F,O+,PA,96281.0,Tricare,062.884.2126,2015-02-28,N
20,04044,Christine,Walker,2007-02-12,F,B+,CA,28365.0,Medicare,(501) 725-7449,2024-07-21,N
21,01589,Janet,Lee,1961-01-31,F,O+,FL,13234.0,Medicare,421.666.7466,2015-09-11,N
22,01556,Elizabeth,Scott,1942-01-21,F,O+,CT,89567.0,Kaiser Permanente,+18445952760,2020-09-13,N
23,01439,Peter,Walker,1955-04-13,M,B+,FL,96056.0,Kaiser Permanente,+15345266346,2011-10-31,N
24,03614,Walter,Smith,1985-12-09,M,A+,FL,17411.0,Humana,574.879.9949,2019-01-03,N
25,03127,Donald,Martin,2001-04-21,M,O+,NY,68949.0,Self-Pay,+19555805815,2010-07-22,N
26,00999,Olivia,Ramirez,2003-09-06,F,A+,MA,49408.0,Self-Pay,823-171-3782,2010-01-12,N
27,02270,James,Rodriguez,1980-08-24,M,O+,OH,38906.0,Medicare,+18645775770,2012-08-20,N
28,00818,Samantha,Moore,2022-08-14,F,O-,FL,20900.0,Kaiser Permanente,NaN,2012-06-16,N
29,00694,Jerry,Moore,1990-12-21,M,O+,CA,94486.0,Medicare,1959903845,2011-09-13,N
30,01336,Susan,Harris,1966-06-17,F,A+,IL,87741.0,Tricare,NaN,2013-04-22,N
31,02818,Margaret,Diaz,1974-04-17,F,B+,OH,17817.0,Medicare,639.234.3391,2021-12-02,N
32,03237,Jennifer,Smith,1937-05-13,F,B+,NY,61160.0,Medicaid,784.561.0722,2011-06-30,N
33,01161,Rebecca,Martinez,1969-08-12,F,O+,CT,45854.0,Tricare,8784511163,2022-11-29,N
34,02477,Carlos,Ramirez,2014-06-19,M,Unknown,MA,51441.0,Medicare,531-561-1401,2014-09-05,N
35,02662,Joyce,Campbell,2009-02-08,F,B-,IL,80907.0,Aetna,+13253632264,2022-09-15,N
36,01213,Dennis,Williams,2000-07-14,M,A+,IL,36900.0,Tricare,4391980720,2023-06-26,Y
37,03407,Melissa,Garcia,1980-12-23,F,B+,TX,74348.0,Self-Pay,+18272328773,2020-12-18,N
38,01754,Dennis,Brown,1970-03-10,M,O+,OH,47934.0,Humana,+14634823120,2016-01-29,Y
39,00906,Edward,Baker,1953-12-01,M,O-,FL,65796.0,Humana,(041) 324-7451,2024-09-09,Y
40,00401,Brenda,Brown,1945-01-14,F,O+,IL,78063.0,Self-Pay,5274955943,2022-06-27,N
41,04008,Margaret,Lewis,1960-09-02,F,O-,NJ,55543.0,Blue Cross Blue Shield,614.013.9900,2017-01-15,N
42,00227,Kimberly,Williams,1942-12-13,F,O+,NY,68388.0,Self-Pay,969.914.1099,2017-02-19,N
43,03511,Patricia,King,1968-04-04,F,A+,OH,71538.0,Aetna,1349687952,2015-09-30,N
44,01935,Brandon,Edwards,1945-12-21,M,O-,CA,81341.0,Self-Pay,8235286524,2023-03-10,N
45,01747,Jonathan,Torres,1936-10-04,M,AB+,CT,14688.0,Medicaid,5977021934,2011-05-13,N
46,00779,Ryan,Hernandez,1932-10-05,M,O+,CA,92549.0,Aetna,(429) 812-5443,2018-02-19,N
47,00950,George,Nelson,1981-08-26,M,A+,CT,30553.0,Blue Cross Blue Shield,0936956068,2024-03-22,N
48,03316,David,Flores,1991-05-31,M,O+,CA,63747.0,UnitedHealthcare,(417) 971-5101,2011-10-28,Y
49,00721,Jennifer,Jackson,1966-03-26,F,A+,TX,29475.0,Aetna,(950) 801-2174,2014-08-05,Y

In [69]:
patients['insurance_provider'].value_counts()

Kaiser Permanente         395
UnitedHealthcare          389
Aetna                     388
Medicare                  380
Cigna                     358
Self-Pay                  355
Tricare                   353
Blue Cross Blue Shield    350
Humana                    344
Medicaid                  332
Name: insurance_provider, dtype: int64

In [70]:
patients=patients.drop(columns='phone')
patients.head(50)

,patient_id,first_name,last_name,date_of_birth,gender,blood_type,state,zip_code,insurance_provider,registration_date,chronic_condition_flag
0,00984,Sharon,Hall,2013-12-09,F,A+,TX,25865.0,UnitedHealthcare,2022-03-11,N
1,01865,Victoria,Williams,1938-11-26,F,O+,IL,89911.0,Tricare,2020-07-17,N
2,00032,Amy,Johnson,1947-06-19,F,A+,NJ,56848.0,Medicaid,2015-09-26,Y
3,02473,Sarah,Garcia,1976-10-13,F,O+,CA,55898.0,Self-Pay,2013-05-20,N
4,03804,Amy,Johnson,2008-05-29,F,O+,TX,60856.0,Humana,2018-02-20,N
5,03251,Donna,Campbell,1975-03-16,F,AB+,FL,24158.0,Cigna,2016-12-14,N
6,01064,Brandon,Flores,1982-03-10,M,O+,IL,80514.0,Cigna,2021-11-06,N
7,02447,Linda,Sanchez,2007-02-04,F,O-,IL,65850.0,Humana,2018-04-27,N
8,00965,Nathan,Wilson,2016-08-20,M,Unknown,NJ,20299.0,UnitedHealthcare,2022-10-22,N
9,02952,Helen,Garcia,2000-08-09,F,AB+,NY,48926.0,Aetna,2012-09-16,N
10,02658,Joseph,Scott,1943-05-08,M,A+,CA,54955.0,UnitedHealthcare,2022-04-15,N
11,00704,Jerry,Wright,1943-08-31,M,B+,PA,63089.0,Cigna,2012-10-02,N
12,00186,Rachel,Taylor,1950-01-12,F,O+,CA,98478.0,Aetna,2010-04-19,Y
13,01849,Brenda,Harris,1932-12-22,F,B-,NY,93461.0,Aetna,2022-08-12,N
14,02547,Betty,Walker,1966-05-12,F,O+,CT,40995.0,Cigna,2012-03-09,N
15,00389,Kimberly,Flores,1944-01-23,F,Unknown,IL,94547.0,Self-Pay,2012-02-25,Y
16,02118,Edward,Smith,1979-12-18,M,O+,OH,34859.0,Cigna,2019-02-03,N
17,03845,Katherine,Ramirez,1950-08-11,F,O+,MA,20008.0,Aetna,2017-01-30,Y
18,00129,Sarah,Gonzalez,1943-03-26,F,AB-,TX,44925.0,Humana,2016-10-26,N
19,03285,Michelle,Moore,1997-12-30,F,O+,PA,96281.0,Tricare,2015-02-28,N
20,04044,Christine,Walker,2007-02-12,F,B+,CA,28365.0,Medicare,2024-07-21,N
21,01589,Janet,Lee,1961-01-31,F,O+,FL,13234.0,Medicare,2015-09-11,N
22,01556,Elizabeth,Scott,1942-01-21,F,O+,CT,89567.0,Kaiser Permanente,2020-09-13,N
23,01439,Peter,Walker,1955-04-13,M,B+,FL,96056.0,Kaiser Permanente,2011-10-31,N
24,03614,Walter,Smith,1985-12-09,M,A+,FL,17411.0,Humana,2019-01-03,N
25,03127,Donald,Martin,2001-04-21,M,O+,NY,68949.0,Self-Pay,2010-07-22,N
26,00999,Olivia,Ramirez,2003-09-06,F,A+,MA,49408.0,Self-Pay,2010-01-12,N
27,02270,James,Rodriguez,1980-08-24,M,O+,OH,38906.0,Medicare,2012-08-20,N
28,00818,Samantha,Moore,2022-08-14,F,O-,FL,20900.0,Kaiser Permanente,2012-06-16,N
29,00694,Jerry,Moore,1990-12-21,M,O+,CA,94486.0,Medicare,2011-09-13,N
30,01336,Susan,Harris,1966-06-17,F,A+,IL,87741.0,Tricare,2013-04-22,N
31,02818,Margaret,Diaz,1974-04-17,F,B+,OH,17817.0,Medicare,2021-12-02,N
32,03237,Jennifer,Smith,1937-05-13,F,B+,NY,61160.0,Medicaid,2011-06-30,N
33,01161,Rebecca,Martinez,1969-08-12,F,O+,CT,45854.0,Tricare,2022-11-29,N
34,02477,Carlos,Ramirez,2014-06-19,M,Unknown,MA,51441.0,Medicare,2014-09-05,N
35,02662,Joyce,Campbell,2009-02-08,F,B-,IL,80907.0,Aetna,2022-09-15,N
36,01213,Dennis,Williams,2000-07-14,M,A+,IL,36900.0,Tricare,2023-06-26,Y
37,03407,Melissa,Garcia,1980-12-23,F,B+,TX,74348.0,Self-Pay,2020-12-18,N
38,01754,Dennis,Brown,1970-03-10,M,O+,OH,47934.0,Humana,2016-01-29,Y
39,00906,Edward,Baker,1953-12-01,M,O-,FL,65796.0,Humana,2024-09-09,Y
40,00401,Brenda,Brown,1945-01-14,F,O+,IL,78063.0,Self-Pay,2022-06-27,N
41,04008,Margaret,Lewis,1960-09-02,F,O-,NJ,55543.0,Blue Cross Blue Shield,2017-01-15,N
42,00227,Kimberly,Williams,1942-12-13,F,O+,NY,68388.0,Self-Pay,2017-02-19,N
43,03511,Patricia,King,1968-04-04,F,A+,OH,71538.0,Aetna,2015-09-30,N
44,01935,Brandon,Edwards,1945-12-21,M,O-,CA,81341.0,Self-Pay,2023-03-10,N
45,01747,Jonathan,Torres,1936-10-04,M,AB+,CT,14688.0,Medicaid,2011-05-13,N
46,00779,Ryan,Hernandez,1932-10-05,M,O+,CA,92549.0,Aetna,2018-02-19,N
47,00950,George,Nelson,1981-08-26,M,A+,CT,30553.0,Blue Cross Blue Shield,2024-03-22,N
48,03316,David,Flores,1991-05-31,M,O+,CA,63747.0,UnitedHealthcare,2011-10-28,Y
49,00721,Jennifer,Jackson,1966-03-26,F,A+,TX,29475.0,Aetna,2014-08-05,Y

In [71]:
patients=patients.set_index('patient_id')
patients.head(50)

,first_name,last_name,date_of_birth,gender,blood_type,state,zip_code,insurance_provider,registration_date,chronic_condition_flag
patient_id,,,,,,,,,,
00984,Sharon,Hall,2013-12-09,F,A+,TX,25865.0,UnitedHealthcare,2022-03-11,N
01865,Victoria,Williams,1938-11-26,F,O+,IL,89911.0,Tricare,2020-07-17,N
00032,Amy,Johnson,1947-06-19,F,A+,NJ,56848.0,Medicaid,2015-09-26,Y
02473,Sarah,Garcia,1976-10-13,F,O+,CA,55898.0,Self-Pay,2013-05-20,N
03804,Amy,Johnson,2008-05-29,F,O+,TX,60856.0,Humana,2018-02-20,N
03251,Donna,Campbell,1975-03-16,F,AB+,FL,24158.0,Cigna,2016-12-14,N
01064,Brandon,Flores,1982-03-10,M,O+,IL,80514.0,Cigna,2021-11-06,N
02447,Linda,Sanchez,2007-02-04,F,O-,IL,65850.0,Humana,2018-04-27,N
00965,Nathan,Wilson,2016-08-20,M,Unknown,NJ,20299.0,UnitedHealthcare,2022-10-22,N
02952,Helen,Garcia,2000-08-09,F,AB+,NY,48926.0,Aetna,2012-09-16,N
02658,Joseph,Scott,1943-05-08,M,A+,CA,54955.0,UnitedHealthcare,2022-04-15,N
00704,Jerry,Wright,1943-08-31,M,B+,PA,63089.0,Cigna,2012-10-02,N
00186,Rachel,Taylor,1950-01-12,F,O+,CA,98478.0,Aetna,2010-04-19,Y
01849,Brenda,Harris,1932-12-22,F,B-,NY,93461.0,Aetna,2022-08-12,N
02547,Betty,Walker,1966-05-12,F,O+,CT,40995.0,Cigna,2012-03-09,N
00389,Kimberly,Flores,1944-01-23,F,Unknown,IL,94547.0,Self-Pay,2012-02-25,Y
02118,Edward,Smith,1979-12-18,M,O+,OH,34859.0,Cigna,2019-02-03,N
03845,Katherine,Ramirez,1950-08-11,F,O+,MA,20008.0,Aetna,2017-01-30,Y
00129,Sarah,Gonzalez,1943-03-26,F,AB-,TX,44925.0,Humana,2016-10-26,N
03285,Michelle,Moore,1997-12-30,F,O+,PA,96281.0,Tricare,2015-02-28,N
04044,Christine,Walker,2007-02-12,F,B+,CA,28365.0,Medicare,2024-07-21,N
01589,Janet,Lee,1961-01-31,F,O+,FL,13234.0,Medicare,2015-09-11,N
01556,Elizabeth,Scott,1942-01-21,F,O+,CT,89567.0,Kaiser Permanente,2020-09-13,N
01439,Peter,Walker,1955-04-13,M,B+,FL,96056.0,Kaiser Permanente,2011-10-31,N
03614,Walter,Smith,1985-12-09,M,A+,FL,17411.0,Humana,2019-01-03,N
03127,Donald,Martin,2001-04-21,M,O+,NY,68949.0,Self-Pay,2010-07-22,N
00999,Olivia,Ramirez,2003-09-06,F,A+,MA,49408.0,Self-Pay,2010-01-12,N
02270,James,Rodriguez,1980-08-24,M,O+,OH,38906.0,Medicare,2012-08-20,N
00818,Samantha,Moore,2022-08-14,F,O-,FL,20900.0,Kaiser Permanente,2012-06-16,N
00694,Jerry,Moore,1990-12-21,M,O+,CA,94486.0,Medicare,2011-09-13,N
01336,Susan,Harris,1966-06-17,F,A+,IL,87741.0,Tricare,2013-04-22,N
02818,Margaret,Diaz,1974-04-17,F,B+,OH,17817.0,Medicare,2021-12-02,N
03237,Jennifer,Smith,1937-05-13,F,B+,NY,61160.0,Medicaid,2011-06-30,N
01161,Rebecca,Martinez,1969-08-12,F,O+,CT,45854.0,Tricare,2022-11-29,N
02477,Carlos,Ramirez,2014-06-19,M,Unknown,MA,51441.0,Medicare,2014-09-05,N
02662,Joyce,Campbell,2009-02-08,F,B-,IL,80907.0,Aetna,2022-09-15,N
01213,Dennis,Williams,2000-07-14,M,A+,IL,36900.0,Tricare,2023-06-26,Y
03407,Melissa,Garcia,1980-12-23,F,B+,TX,74348.0,Self-Pay,2020-12-18,N
01754,Dennis,Brown,1970-03-10,M,O+,OH,47934.0,Humana,2016-01-29,Y
00906,Edward,Baker,1953-12-01,M,O-,FL,65796.0,Humana,2024-09-09,Y
00401,Brenda,Brown,1945-01-14,F,O+,IL,78063.0,Self-Pay,2022-06-27,N
04008,Margaret,Lewis,1960-09-02,F,O-,NJ,55543.0,Blue Cross Blue Shield,2017-01-15,N
00227,Kimberly,Williams,1942-12-13,F,O+,NY,68388.0,Self-Pay,2017-02-19,N
03511,Patricia,King,1968-04-04,F,A+,OH,71538.0,Aetna,2015-09-30,N
01935,Brandon,Edwards,1945-12-21,M,O-,CA,81341.0,Self-Pay,2023-03-10,N
01747,Jonathan,Torres,1936-10-04,M,AB+,CT,14688.0,Medicaid,2011-05-13,N
00779,Ryan,Hernandez,1932-10-05,M,O+,CA,92549.0,Aetna,2018-02-19,N
00950,George,Nelson,1981-08-26,M,A+,CT,30553.0,Blue Cross Blue Shield,2024-03-22,N
03316,David,Flores,1991-05-31,M,O+,CA,63747.0,UnitedHealthcare,2011-10-28,Y
00721,Jennifer,Jackson,1966-03-26,F,A+,TX,29475.0,Aetna,2014-08-05,Y

In [72]:
patients_cleaned=patients.to_csv('~/Desktop/patients_cleaned.csv')